libxmp/libxmp

src/loaders/it_load.c

The for loop conditional is an attempt at making the incremental's final value
more obvious.

Fixes Removal of Final IT Song Message Character

---

Makefile.in
configure.ac
lite/Makefile.in.in
lite/configure.ac

updates to make it possible building a proper static win32 lib

---

config.guess
config.sub

.. again.  there has been some reverts in the mainstream repo, so this
catches up to it.

update config.guess and config.sub from git://git.sv.gnu.org/config.git

---

src/loaders/imf_load.c

Closes: https://github.com/cmatsuoka/libxmp/issues/142

imf_load: Fix number of envelope points sanity check (was off-by-one)

---

src/loaders/mmd_common.c

Tempos 1 through 10 in tempo mode (and when 8-channel mode is not enabled) are for "tracker compatibility" and roughly approximate Soundtracker speeds 1 through 10. This patch adds compatibility for these tempos and also moves some of the 8-channel tempo checks into a common tempo conversion function (so compatibility checks like these don't have to keep getting duplicated).
The compatibility tempos here are implemented with a table of approximate speeds I found by matching them as close as possible in OctaMED 2.00 and OctaMED 4.00. For each "speed" the compatibility tempo is approximately equal to `tempo = round(195.0 / speed)` but there's some variation. I think there are other ways to implement these if you don't like this (I checked OpenMPT out of curiosity and noticed it uses a …

Fix OctaMED 'tracker compatibility' tempos.

---

test-dev/test.h

The sequel to #182—I should test on things that aren't MSYS2 before submitting a patch :(

Fix test-dev failure message on Windows.

---

test-dev/gen_module_data.py

Our module loading tests currently compare the data loaded from
the module file with reference data prepared by a python script.
Update this script to use python3.

test-dev: update data generation script to use python3

---

.github/workflows/emscripten.yaml

Add emscripten github actions test following Vitaly Novichkov's
recommendations.

github/workflow: add emscripten test

---

.github/workflows/coverage.yaml

Create a GitHub actions workflow to verify test coverage and upload it to codecov.io.

github/workflows: add code coverage

---

.github/codecov.yml

Add codecov status configuration. We may need to adjust this to
obtain the results we want.

Add codecov configuration

---

src/hio.c
src/load.c
src/loaders/pw_load.c
test-dev/Makefile.in
test-dev/all_tests.txt
test-dev/configure.ac
test-dev/test_read_file_hio_pipe.c

Closes: https://github.com/libxmp/libxmp/issues/338

make hio_open_file() fail if get_size() returns negative

---

src/loaders/s3m_load.c

This compatibility check was added to fix a broken version of "Return of Litmus" that existed circa 2007. This broken version no longer seems to be available, and all copies I can find are not corrupted. Furthermore, support for this hack was broken anyway due to several sanity checks on the affected variables having been added. The previously reported behavior of libxmp hanging at 100% CPU usage when loading this broken module should no longer occur.
Fixes #360.

Remove 'quirk87' handling from the S3M loader.

---

Makefile.nt
Makefile.os2
lite/Makefile.nt
lite/Makefile.os2
lite/watcom.mif.in
watcom.mif
watcom.mif.in

This works on Windows, but hasn't been fully tested for OS/2.

Add check target to OpenWatcom makefiles

---

docs/CREDITS

GitHub wants CI checks to pass for this even though it doesn't touch source files... oh well 🙃

Update docs/CREDITS for 4.5.0.

---

.github/workflows/sanitizers.yaml

Testing to see if this is enough to get these to work...

Add AddressSanitizer and MemorySanitizer workflows.

---

.github/workflows/regression.yaml

Add Ubuntu gcc-10/-flto regression test.

---

src/depackers/vorbis.c

Removes the following checks that no longer do anything useful:
* `compute_codewords` `len[k] >= 32`: obsoleted by bounds checking lengths when they're read in `start_decoder`.
* `compute_codewords` `z >= 32`: obsoleted by bounds checking lengths when they're read in `start_decoder`.
* `draw_line` `adx==0`: obsoleted by `lx != hx` in `do_floor`.
* `draw_line` `x >= n*2`: obsoleted by clamping `x1` to `n`.
* `draw_line` `y >= 256` (two places): obsoleted by indexing with `y&255`.
* `draw_line` return value: obsoleted by removal of previous checks.
Removing these gets the libxmp copy of stb_vorbis a little closer to upstream. I haven't vetted all of the extra checks that libxmp adds, but these ones were fairly easy.

Remove stb_vorbis sanity checks that are no longer required.

---

test-dev/main.c
test-dev/test.h
test-dev/test_effect_0_arpeggio.c
test-dev/test_effect_1_slide_up.c
test-dev/test_effect_2_slide_down.c
test-dev/test_effect_4_vibrato.c
test-dev/test_effect_fine_vibrato.c
test-dev/test_effect_it_vcol_g.c
test-dev/test_effect_note_slide.c
test-dev/test_effect_note_slide_retrig.c
test-dev/test_effect_okt_arpeggio.c
test-dev/test_effect_per_slide.c
test-dev/test_effect_per_toneporta.c
test-dev/test_effect_persistent_slide.c
test-dev/test_effect_persistent_vibrato.c
test-dev/test_player_period_mod_range.c

Fix compiling the unit tests with C89 compilers

---

src/depackers/vorbis.c

Fixes: https://github.com/libxmp/libxmp/issues/434

vorbis depacker: respect stb_vorbis_get_frame_float() error returns

---

configure.ac
lite/configure.ac

also fix wrong autoconf cache variable use for -Werror.

add -Wwrite-strings to CFLAGS if it's available

---

.gitignore
test-dev/Makefile.in
test-dev/libxmp_fuzz.c
test-dev/libxmp_fuzz.sh

Based on Lionel Debroux's initial libFuzzer frontend from #302.
@debrouxl any thoughts/recommendations?

Add libFuzzer frontend for libxmp.

---

src/depackers/bunzip2.c
src/depackers/uncompress.c
src/loaders/ims_load.c
src/loaders/prowizard/p40.c
src/loaders/prowizard/p61a.c
src/loaders/prowizard/theplayer.c
src/loaders/st_load.c
src/mix_paula.c

Fixes #469. Commit 1 fixes everything but the -Wclobbered in bunzip2.c and commit 2 just fixes the -Wclobbered. I haven't verified this actually works yet since the warning doesn't happen locally for me.
edit: there are two more I missed...

Fix more -Wunused-but-set-variable warnings.

---

src/depackers/vorbis.c

This removes more of the libxmp-specific checks and other changes that do absolutely nothing. I don't blame anyone for thinking that these *could* do something because the backtracking for some of these cases is getting absurd.
I'll comment each change with the justification this time instead of dumping it all in the initial post.
edit: OK, each removed check has a comment thread now. As a final note, I checked the commit history for vorbis.c and most of these were added circa 2015 and their commit messages don't point to any reported issue they fixed (this doesn't mean they don't exist). I'm marking this for review but I do want to fuzz it a bit before merge.

Remove stb_vorbis sanity checks that are not required (again).

---

src/depackers/vorbis.c

More of the same as #473, except this time it should be the last one. Like last time, I'm going to stick the explanations in review comments because some of them are long. This reverts a couple of recent patches (#269 and #441) fixing bugs caused by negative return values that were actually libxmp's fault in the first place—at some point the libxmp fork was modified to use Unix-style 0/-1 return values in some places where stb_vorbis consistently used `TRUE`/`FALSE` or lengths.
edit: all major issues have review comments explaining them now. Places that aren't commented are generally related to the `vorbis_pump_first_frame`/`vorbis_finish_frame` issue or are from the aforementioned patches that are no longer necessary.

Remove remaining stb_vorbis sanity checks that are not required.

---

src/depackers/mmcmp.c

Fixes one of the issues in #517: files ending with an 8-bit compressed block shorter than 256 bytes would be rejected because the ptable handling was incorrectly adapted from libmodplug.

Fix bad seeking behavior in MMCMP compressed blocks.

---

src/depackers/mmcmp.c

libmodplug is the gift that keeps giving

Fix uninitialized reads caused by odd length 16-bit MMCMP blocks.

---

src/depackers/depacker.c

This seems like a regression: `libxmp_decrunch` should never allow the `HIO_HANDLE` to be `NULL` because various places in load.c will attempt to close it, resulting in a crash.
Found with this Zip64 archive. The returned length ends up being `(size_t)UINT32_MAX`, which overflows to `(long)-1` in Windows, causing `hio_open_mem` to fail. That length is definitely a Zip64 placeholder for the 32-bit length field rather than a real length, but I haven't diagnosed it yet (the bug could plausibly be in either unzip.c or in miniz).
[ponylips.64.zip](https://github.com/libxmp/libxmp/files/7784434/ponylips.64.zip)
edit: it's absolutely a miniz bug: `mz_zip_reader_extract_to_heap` reads the 32-bit values out of the central directory header without so much as checking them for Zip64.

Don't allow libxmp_decrunch to return a NULL HIO_HANDLE.

---

src/depackers/miniz.h
src/depackers/miniz_tinfl.c

See:  https://github.com/richgel999/miniz/pull/159

miniz: apply mainstream PR/159 to reduce inflate memory usage

---

src/depackers/xfd.c
src/depackers/xfd_link.c

Relicense XFD decruncher under MIT (with permission of Chris Young).

---

src/loaders/vorbis.c

Fixes strict-aliasing warnings from older gcc versions:
src/loaders/vorbis.c: In function 'start_decoder':
src/loaders/vorbis.c:3831: warning: dereferencing type-punned pointer will break strict-aliasing rules
src/loaders/vorbis.c:3888: warning: dereferencing type-punned pointer will break strict-aliasing rules
src/loaders/vorbis.c:3889: warning: dereferencing type-punned pointer will break strict-aliasing rules
src/loaders/vorbis.c:3890: warning: dereferencing type-punned pointer will break strict-aliasing rules
src/loaders/vorbis.c:3969: warning: dereferencing type-punned pointer will break strict-aliasing rules
src/loaders/vorbis.c: In function 'vorbis_deinit':
src/loaders/vorbis.c:4328: warning: dereferencing type-punned pointer will break strict-aliasing rules …

vorbis: eliminate type-punned pointer use

---

src/callbackio.h
src/dataio.c
src/loaders/mdl_load.c
src/loaders/xm_load.c
src/mdataio.h
test-dev/Makefile.in

Closes: https://github.com/libxmp/libxmp/issues/542

miscellenaous small stuff

---

src/depackers/miniz.h
src/depackers/miniz_tinfl.c

Updates from https://github.com/richgel999/miniz/pull/159 after PR #529 merge.

miniz_tinfl: updates from mainstream PR/159

---

src/depackers/arc_unpack.c

This struct had the same name as a function libxmp renames with a define, which was *probably* OK, but still tacky and not consistent with the LZX depacker.

Rename struct arc_unpack to struct arc_data.

---

.github/workflows/regression.yaml
Makefile.dos

See also https://github.com/libxmp/xmp-cli/pull/42#issuecomment-1057520847

Support compiling for MS-DOS with OpenWatcom

---

src/loaders/mod_load.c

* Use `patbuf` for libxmp-lite, which is faster and removes a lot of #ifdef junk.
* Revert extra `\n` added to the instrument debug line.
* Move `magic` out of preprocessor branches, move `idbuffer` to the one spot it is actually used.
* Move Digital Tracker extra bytes skip to immediately after this format is detected, and move libxmp-lite `libxmp_set_type` next to the full library equivalent.
I think the only noticeable difference this should cause is libxmp-lite with `-DDEBUG` will print the module info in the same place the full library does now instead of earlier.
Draft until Github confirms this didn't break libxmp-lite : )

Tidy unified MOD loader from #595.

---

src/loaders/med.h
src/loaders/rtm_load.c

Closes https://github.com/libxmp/libxmp/issues/614

remove amiga/windows types use in med.h and rtm_load.c.

---

.github/workflows/regression.yaml
test-dev/Makefile.in

Should be futureproofed against further unnecessary CMake nonsense now. :)

Stop breaking the fuzzers.

---

src/loaders/xmf_load.c

CC @AliceLR
These are the additional sanity checks I use in OpenMPT. I guess the middle-C frequency check may be a bit questionable as it is not *technically* wrong, but given the low number of valid modules that actually exist, it can help catching some sparse binary files disguising as XMFs.

XMF: tighten sample header validation

---

include/xmp.h

This is pretty self explanatory. I *think* the rest can wait for 4.6.1 or something.

Add stereo sample flag to xmp.h.

---

src/loaders/xmf_load.c

Through the magic of asking nicely, @sagamusix was able to acquire playercode and some more modules in the XMF format. These extra modules use a `0x04` for the first byte instead of `0x03`, and are mixed at normal volume levels (rather than for Imperium Galactica's extremely loud Sound Blaster driver).
A test `0x04` variant is available in [this demo](https://www.pouet.net/prod.php?which=2234) (filename PROSTATE.MUS).
edit: codecov is almost right. Diff coverage is 56%, file loses 1.16% coverage, mainly because of the new effect.

Rename XMF loader to 'Astroidea XMF', add support for 0x04 variant.

---

src/depackers/bunzip2.c

- fix `src/depackers/bunzip2.c:550: warning: argument 'len' might be clobbered by 'longjmp' or 'vfork'`
from old gcc versions
- fix `src/depackers/bunzip2.c:553: warning: variable 'gotcount' might be clobbered by 'longjmp' or 'vfork'`
from really old gcc versions
- remove unused parameter from burrows_wheeler_prep()
- restore original names of two error return macros

bunzip2 longjmp warning fixes and tidy-up

---

src/depackers/lzx_unpack.c
test/test.c

Not sure how this slipped past before now...

Fix LZX and test -Wstrict-prototypes warnings.

---

src/depackers/arc.c
src/depackers/arcfs.c
src/depackers/lzx.c
src/depackers/unsqsh.c
src/depackers/unxz.c
src/depackers/unzip.c
src/load.c
src/loaders/mmd_common.c
src/loaders/s3m.h
src/loaders/umx_load.c
src/memio.c
src/period.c

update copyright years of the sources touched after the last time.

---

src/loaders/mod_load.c

1) Finding any instance of EFx in a "Noisetracker" MOD switches tracker ID to Protracker immediately during pattern loading (to allow the loading of these effects).
2) Finding any instance of EFx in a MOD without any "decisive" tracker ID result and with all notes in-range switches tracker ID to Protracker unless it is already OpenMPT (to allow playing of EFx as invert loop).
I also added a bunch of debug printing for tracker ID in a second commit. It might be more helpful to read the two commits separately.
This resolves a SIDE issue discussed in #717, but does not affect the primary reported issue there. For a breakdown of the affected MODs, [here is a spreadsheet](https://docs.google.com/spreadsheets/d/12M2qpdDtkG6pBTFZva4ldMwEtInybjOllC43xoNKCjQ/edit?usp=sharing). Out of the 87 total …

Make the presence of invert loop override tracker ID guesses.

---

src/mixer.c

mixer.c was handling sample loops in two different places:
1) If the end of the tick exactly coincided with the channel reaching the end of its loop, it would be looped immediately before the mixer continued to the next channel.
2) If the end of the sample was reached prior to the end of the tick, it would be looped after checking for a one-shot sample.
This originally wasn't too horrible, but the addition of reverse samples and resampling wraparound management bloated it. Fixing Protracker sample swaps (#717) is going to bloat it further. These two cases were mostly equivalent, so I combined the former into the latter.
Oktalyzer split channel support is affected by this, but most likely the change is a net positive. When a sample plays in an Oktalyzer split channel, it is not supposed to …

Clean up jank in mixer.c sample loop handling.

---

docs/Changelog
lite/Changelog
src/effects.c
src/loaders/common.c
src/loaders/med2_load.c
src/loaders/med3_load.c
src/loaders/med4_load.c
src/loaders/mmd1_load.c
src/loaders/mmd3_load.c
src/loaders/mod_load.c
src/loaders/sym_load.c
src/loaders/ult_load.c
src/virtual.c

Some of the changelog entries might be better worded?
Feel free to edit / push to this branch for it.

update 4.6.1 changelog, update copyright years of recently touched srcs

---

src/loaders/dt_load.c

* Digital Tracker versions 2.015 and 2.02 (and most likely the missing 2.025) supported DTM as well, despite the UI advertising it as "MOD". I let the UI confuse me when I wrote these comments despite the 2.015 digi_tal.txt clearly stating that it is the first version with the new format.
* I forgot to test effect Fxx in earlier versions of Digital Tracker. 1.01 through 2.02 share the behavior of 2.03 and the beta acts more like a VBlank MOD tracker (and since it only outputs M.K., VBlank detection should support it).
> Version 2.15
> 
> DEMO KIT of DIGIPLAY and DIGITAL TRACKER F030 by MC JEE from KAMIKAZES
> 
> Toulouse 23/2/94 France
> 
> Digital Tracker
> 
> Hello, I'm put this intermediate version because of new format in
> export for the modules, instruments,...
> This format is …

Fix some misinformation in the DTM loader comments.

---

docs/Changelog
src/loaders/it_load.c

update changelog for 4.6.2, update copyright years in relevant sources.

---

src/loaders/vorbis.c
src/loaders/vorbis.h

(sample-accurate-tell stuff excluded)

vorbis: sync with stb_vorbis-sezero branch in sezero's fork stb.

---

docs/CREDITS
docs/libxmp.rst
docs/style.css

- docs/style.css: add missing newline at end of file
- docs/CREDITS: add Thomas Neumann among list of authors.
- docs/libxmp.rst: Fix typos from PR/853
I _believe_ those were typos..
Fixes errors in pdf generation:
```
docs/pdfdoc.rst:542: (ERROR/3) Unknown target name: "xmp_set_tempo_factor".
docs/pdfdoc.rst:722: (ERROR/3) Unknown target name: "xmp_set_tempo_factor".
docs/pdfdoc.rst:722: (ERROR/3) Unknown target name: "xmp_scan_module".
docs/pdfdoc.rst:828: (ERROR/3) Unknown target name: "xmp_get_frame_info".
docs/pdfdoc.rst:828: (ERROR/3) Unknown target name: "xmp_scan_module".
```

updates to docs/*

---

docs/Changelog
src/loaders/dt_load.c

Fix Digital Tracker instrument finetune field.
