- src/loaders/sample.c
Hello, please consider the following patch for inclusion in the official repository.
I am not sure of the exact intent of the original code but it was clearing causing quality problems as you can see below. The code was duplicating the last sample of the instrument loop end before copying samples from the loop start.
The picture was done while debugging [`explora.xm` by Clawz](http://modarchive.org/index.php?request=view_by_moduleid&query=140994) at roughly 23 seconds in the lead synth sounds very dirty even when spline interpolation is used.
No regression was noted on various .mod and .xm I tested.
> Fix the sample loop correction code.

- .travis.yml
This way, some memory safety problems will be caught earlier.
Travis is failing with this patch, because the testsuite currently triggers a few uses of uninitialized memory and and out of bounds reads.
> .travis.yml: add clang-with-ASan and clang-with-MSan as "compilers"

- src/loaders/it_load.c
I noticed with IT files that volume-column panning parameters of both 64
(the max) and 63 resulted in identical panning.  This patch corrects
that.
> Fix for IT's Volume Panning Effect

- src/loaders/it_load.c
The IT message length includes the null terminator, yet up until now, libxmp has allocated an extra character for a null terminator.  This has resulted in every IT song message being appended with an extraneous period.
> IT Message (Comment) Length Miscalculation

- lite/src/format.c
- lite/src/loaders/mod_load.c
Currently trying to use the lite version fails with undefined
references to the old format loader names.
This bug was introduced in d018decfb98d: "Add prefix to format loaders"
> Fix libxmp-lite building (wrong format loaders)

- src/depackers/vorbis.c
- src/loaders/prowizard/fuchs.c
- src/memio.c
The lookup_values warning was valid. The other three were bogus, but silenced them anyway.
src/depackers/vorbis.c(981): Warning! W107: Missing return value for function 'get8'
src/depackers/vorbis.c(1010): Warning! W107: Missing return value for function 'getn'
src/depackers/vorbis.c(3609): Warning! W136: Comparison equivalent to 'unsigned == 0'
src/depackers/vorbis.c(4299): Warning! W107: Missing return value for function 'stb_vorbis_get_file_offset'
> src/depackers/vorbis.c: Fix warnings:

- configure.ac
-lm seems to add about 15k to the dylib size..
> -lm not needed with darwin.

- src/loaders/it_load.c
Previously, libxmp would return an error upon loading an IT file containing an instrument envelope with an impossibly large number of nodes.  Now, it clamps to the IT spec maximum (25).  The new behavior has been tested to match Impulse Tracker, Schism Tracker, and DUMB.
> Clamp Number of IT Envelope Nodes at Load Time

- include/xmp.h
- src/control.c
EXPORT is a dangerously common name
> rename EXPORT to LIBXMP_EXPORT

- src/effects.c
This fixes a bug with .it playback (#97) where, when the end of a loop (e.g. SB2) occurs on the same line as a break (e.g. C00), libxmp would attempt to break to the next pattern and go to the start of the loop at the same time.  Instead, it will now ignore the break until the loop is finished.
> Fixed .it bug where Cxx on same row as SBx would not be ignored

- src/effects.c
This fixes a bug with the .it retrigger command (#97) where the volume parameter would be updated only on rows with a note.  With this fix, it will correctly update on any row the retrigger command is present on.
> Fixed .it bug where Qxy would ignore the volume parameter

- src/loaders/it_load.c
localtime_r() is used only in it_load.c and only when LIBXMP_CORE_PLAYER
is not defined. therefore add libxmp_ prefix to the replacement version,
make it static, and add the !LIBXMP_CORE_PLAYER ifdefs around it.
> guard replacement localtime_r() with LIBXMP_CORE_PLAYER

- src/effects.c
Previously, libxmp would ignore `T00` IT effects.  I tested with it214v5 and observed that `T00` does indeed repeat its channel's most recent slide.
> T00 Now Repeats Previous Slide (IT)

- src/loaders/it_load.c
Libxmp was throwing away volume values for IT files' muted channels, even though mute status is completely independent of volume.
> Prevent Clobbering of Muted Channels' Volumes

- src/loaders/gdm_load.c
This patches the GDM loader so it will correctly handle empty notes instead of trying to convert them like a regular note. This fixes STARDSTM.GDM (issue #147), which relies on empty notes.
> Fix GDM loader to correctly handle empty notes

- src/depackers/s404_dec.c
E.g.: one fuzz file gave the following valgrind warnings:
==21740== Invalid read of size 1
==21740==    at 0x401B314: readmem16b (dataio.c:174)
==21740==    by 0x407B0CE: initGetb (s404_dec.c:49)
==21740==    by 0x407B2F3: decompressS404 (s404_dec.c:134)
==21740==    by 0x407BA83: decrunch_s404 (s404_dec.c:408)
==21740==    by 0x4028D37: decrunch (load.c:208)
==21740==    by 0x402964E: xmp_load_module (load.c:498)
==21740==    by 0x804AEF0: main (main.c:398)
==21740==  Address 0x411597d is 0 bytes after a block of size 20,573 alloc'd
==21740==    at 0x40072B2: malloc (vg_replace_malloc.c:270)
==21740==    by 0x407B9A6: decrunch_s404 (s404_dec.c:385)
==21740==    by 0x4028D37: decrunch (load.c:208)
==21740==    by 0x402964E: xmp_load_module (load.c:498)
==21740==    by 0x804AEF0: main …
> depackers/s404_dec.c: revise sanity checks to prevent oob reads.

- test-dev/Makefile.in
- test-dev/md5.h
test-dev/md5.h: remove dependency on sys/cdefs.h .
test-dev/Makefile.in: add win32.o to TEST_INTERNAL objects list.
> test-dev build fixes

- src/memio.c
fixes https://github.com/cmatsuoka/libxmp/issues/156
(I think I handled size<0 case correctly, but please review.)
> memio.c (mseek): just seek to end if offset is past the end of file

- src/depackers/vorbis.c
1. compute_codewords():
- compute_codewords() returns success (boolean), not error: replace one
instance of negative return with FALSE.
- the (k == n) sanity check was duplicated: remove the libxmp-added one
and just return (c->sorted_entries == 0) replacing the assert() along
the way.
2. start_decoder():
- sanity checks added by libxmp hadn't set the error value, now they do.
also fixes a wrong return value of -1 instead of FALSE.
> depackers/vorbis.c: fix sanity check error returns

- src/loaders/s3m_load.c
This branch fixes playback of S3Ms containing ADPCM4 samples using the same method libmodplug uses to detect them. 
Example S3M file that relies on ADPCM4 samples: [mm2flash.s3m.zip](https://github.com/cmatsuoka/libxmp/files/4432582/mm2flash.s3m.zip) (seems to be a resaved copy of [this](https://modarchive.org/index.php?request=view_by_moduleid&query=50304)).
> Fix S3M ADPCM4 samples

- src/loaders/gdm_load.c
This branch fixes playback of GDM fine slide effects that are followed by continue effects. Since GDMs were typically converted S3Ms, they sometimes contain effect continue commands intended for fine effects (e.g. `A00` to continue `EA4`). The easiest way to fix this was to just enable `QUIRK_FINEFX` for GDMs and convert these effects back to their S3M equivalents. The following extended effects are affected:
* `EX_F_PORTA_UP` → `FX_PORTA_UP` (`Fy`)
* `EX_F_PORTA_DN` → `FX_PORTA_DN` (`Fy`)
* `0x8` → `FX_PORTA_UP` (`Ey`)
* `0x9` → `FX_PORTA_DN` (`Ey`)
* `EX_F_VSLIDE_UP` → `FX_VOLSLIDE` (`xF`)
* `EX_F_VSLIDE_DN` → `FX_VOLSLIDE` (`Fy`)
These changes are based on [MenTaLguY's GDM format documentation](https://github.com/AliceLR/megazeux/blob/master/contrib/gdm2s3m/doc/gdm.txt). If you're …
> Fix GDM fine extended effects continue

- src/tempfile.c
this has been missed for quite some time.
> tempfile.c: include common.h to retrieve libxmp_snprintf() defines.

- src/loaders/far_load.c
This patch fixes the handling of volume events in .FAR modules, which caused a weird bug where 0 volume events would be ignored. Despite [what the .FAR documentation says](https://modland.com/pub/documents/format_documentation/Farandole%20Composer%20(.far).txt), .FAR volume events are encoded like:
* `0x00` → no change
* `0x01` → volume=0
* `0x02` → volume=1
...
* `0x10` → volume=15
I generated some raw pattern data dumps to compare to screenshots from Farandole Composer to show this. The third byte is the volume. `0x00` is shown as blank spaces. I omitted parts of the patterns so there's less text to sift through.
[rainruin.far.zip](https://github.com/cmatsuoka/libxmp/files/5400091/rainruin.far.zip)
```
: pattern 16: length=2050, expected_rows=32, break byte=30, difference=2
: 05 01 0a …
```
> Fix volume event handling for .FAR modules.

- docs/libxmp.rst
- src/hio.c
- src/hio.h
- src/load.c
- src/loaders/alm_load.c
- src/loaders/pw_load.c
- src/loaders/ssmt_load.c
cf.: https://github.com/cmatsuoka/libxmp/pull/173
for internal uses of hio_open_file, invent new hio_open_file2() which
does allow the library to close the file.
> don't use fdopen() in hio_open_file, leave closing the file to caller:

- src/control.c
Currently, `xmp_set_position`/`xmp_next_position`/et al. do not consistently clear the pattern break and jump variables in the player flow struct, meaning if these functions are called between this effect being used and the next row playing, the first row of the position set by `xmp_set_position`/etc. will play and then the pattern break or pattern jump will immediately take effect. Believe it or not, this was actually causing an audio bug in [a MegaZeux game](https://www.digitalmzx.com/show.php?id=2223) due to some unfortunate timing.
This patch simply makes these functions clear the relevant pattern flow variables whenever the player position is modified. It might also be necessary to clear `f->loop_chn` and `f->rowdelay` (not entirely sure).
> Make xmp_set_position consistently clear pattern break/jump vars

- src/common.h
- src/win32.c
The usage of libxmp_snprintf and libxmp_vsnprintf in Windows not necessary for MSVC 2015+ and for MinGW with `__USE_MINGW_ANSI_STDIO` defined (which appears to be the default), as C99 compliant versions of these functions will be used in these cases. Using these functions (which exist in a separate compilation unit) instead of the regular implementations prevents potential optimizations that compilers may be able to do [when snprintf is a built-in function](https://gcc.gnu.org/onlinedocs/gcc-5.2.0/gcc/Other-Builtins.html).
[MSVC documentation of snprintf](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/snprintf-snprintf-snprintf-l-snwprintf-snwprintf-l?view=vs-2019) notes that since MSVC 2015, snprintf is C99 compliant.
[MSVC documentation of …
> Don't use libxmp_snprintf for MSVC 2015+ and MinGW

- src/load.c
- src/loaders/amf_load.c
- src/loaders/gal4_load.c
- src/loaders/gal5_load.c
- src/loaders/iff.c
- src/loaders/imf_load.c
- src/loaders/masi_load.c
- src/loaders/mdl_load.c
- src/loaders/med4_load.c
- src/loaders/psm_load.c
- src/loaders/rtm_load.c
- src/loaders/stm_load.c
Fixes a bunch of annoying GCC 10(?) warnings caused by usage of strncpy. Some of the strncpy uses were legitimate but a few (like the Galaxy, PSM, and RTM loaders) were potentially cutting off terminating nulls.
Also fixes an operator precedence error from https://github.com/cmatsuoka/libxmp/pull/93 that GCC caught but somehow none of us noticed (sorry!).
> Fix GCC stringop-truncation warnings.

- src/loaders/iff.c
Reverts a faulty warning fix from commit c7dccce6. This was the rare legitimate usage of strncpy and I didn't realize this function gets provided id strings shorter than 4 bytes (happens in the MDL loader...).
> Revert -Wstringop-truncation fix in libxmp_iff_register.

- src/loaders/mmd_common.c
This fixes a few minor OctaMED effects bugs.
* The slide up and slide down commands `1xx` and `2xx` should ignore a param of 0.
* The fine volume up and down commands `1Axx` and `1Bxx` should ignore a param of 0.
* The speed effect had faulty bounding (it is bounded between `0x01` and `0x20`, not 1 and 20).
There are some other missing or buggy commands here that I left alone because I'm not sure how to implement several of them right now.
* MMD0 `5xx` (old vibrato) isn't implemented (a small number of modules use this).
* `8xx` (set hold and decay) does nothing. There's an effect reserved that does nothing but also a second hold effect implemented in med_extras.c that sets the hold (but not decay).
* `Exx` (synth jump) does nothing.
* `FF4` and `FF5` (delay note one third of a line, …
> Ignore MED volume/slide effects with param of 0, fix speed bound.

- configure.ac
- lite/configure.ac
- src/loaders/common.c
- src/loaders/it_load.c
- src/loaders/loader.h
- src/loaders/s3m_load.c
Fixes several issues with the calculation of Schism Tracker dates.
* The date calculation was using a UTC epoch time but calculating the version date with localtime_r instead of gmtime_r (maybe because Schism uses localtime_r... the difference is Schism generates its epoch time with mktime).
* The UTC epoch time was wrong (2009-10-01 instead of 2009-10-31).
* The S3M loader was not calculating Schism Tracker dates at all.
* Added detection for extended Schism Tracker dates (>2020-10-28) to both the S3M and IT loaders.
Fixes #154. I think I got this right, but this should *really* be reviewed by @sagamusix before it's merged.
edit: this sure doubles the number of spurious format truncation warnings for Schism Tracker dates though. 🙄
> Fix Schism Tracker version date calculation.

- src/loaders/iff.h
This fixes the loading of several DigiBooster Pro modules with sample chunks larger than 4 MiB, of which I found >=22 in the ModLand collection. Fixes #166.
> Increase maximum IFF chunk size to 8 MiB.

- src/loaders/common.c
- src/loaders/loader.h
- src/loaders/mmd1_load.c
- src/loaders/mmd3_load.c
This fixes some MED bugs I found while looking into why the module "New Dimension" does not load.
* This MED contains patterns with lengths greater than 256. MMD1+ patterns use a word to store the pattern length but I'm not sure what a realistic bound for this is (edit: it's 3200 judging by the docs). The fix for this in this patch should be revised BEFORE this is merged because the 256 row sanity check assumption is true for most other formats and 32768 is an arbitrary number I chose for testing. Do you have any recommendations for a better way to do this @sezero?
* The MMD loaders were writing the OctaMED instrument name (40 chars long) directly into the instrument name (32 chars long), corrupting the instrument volume and sample count fields.
* Several spots were not adding `start` to …
> Fix MEDs with pattern lengths >256, MED instrument corruption.

- .travis.yml
Change Travis CI configuration so it can be used to test pull requests.
Travis configuration can be improved later to re-enable clang analyzers
and include native Windows builds.
> update travis-ci configuration

- Makefile.in
- lite/Makefile.in.in
I don't know why it has always been setup to dynamic_lookup,
but macOS dylib builds must not have any undefined symbols.
> dylib: change undefined symbols to be error rather than dynamic lookup.

- Makefile.in
- configure.ac
Use a flag to the configure script to enable and disable depackers
instead of editing the variable directly on the makefile in systems
where the Makefile is generated using autoconf.
OS/2 and VC++ makefiles retain USE_DEPACKERS.
> build: use configure flag to disable depackers

- src/common.h
- src/load.c
- src/load_helpers.c
- src/smix.c
- test-dev/test_api_prev_position.c
- test-dev/test_api_set_position.c
- test-dev/test_api_set_row.c
- test-dev/test_mixer_interpolation_default.c
- test-dev/test_next_order_skip.c
- test-dev/test_player_dct_note.c
- test-dev/test_player_ft2_note_noins_after_invalid_ins.c
- test-dev/test_player_ft2_note_noins_after_keyoff.c
- test-dev/test_player_invalid_mod_channels.c
- test-dev/test_player_invalid_mod_length.c
- test-dev/test_player_invalid_period.c
- test-dev/test_player_nna_cont.c
- test-dev/test_player_nna_cut.c
- test-dev/test_player_nna_fade.c
- test-dev/test_player_nna_off.c
- test-dev/test_player_note_off_ft2.c
- test-dev/test_player_note_off_it.c
- test-dev/test_player_pan.c
- test-dev/test_player_period_amiga.c
- test-dev/test_player_period_mod_range.c
- test-dev/test_player_read_event.c
- test-dev/test_player_virtual_channel.c
- test-dev/test_prev_order_skip.c
- test-dev/test_prev_order_start.c
- test-dev/test_prev_order_start_seq.c
Third of ~~four~~ THREE patches. This fixes trivial leaks in the `test_player_*` and `test_mixer_*` tests, as well as the `libxmp_prepare_scan`-related leaks documented in #110. The first two sets were the same `xmp_release_module`/`xmp_free_context` copypaste as everywhere else, but the `libxmp_prepare_scan` fix required a new function.
This should be the last of the patches for trivial leaks in the tests. No promises these patches will get the CI ASan checks working again, but this might significantly reduce the log spam (going off of what I saw in the logs for #109). ~~The only problem left when I run `make devcheck` with ASan enabled is `test_api_test_module` leaking hio handles, which may or may not be related to #178.~~ It was a single wrong function call unrelated to that PR and I …
> Fix test-dev player, mixer, and libxmp_prepare_scan leaks.

- src/loaders/amf_load.c
- src/loaders/liq_load.c
- test-dev/util.c
Address code indent and typecast warnings issued when building with
clang on Ubuntu Groovy.
> loaders,test-dev: address clang warnings

- configure.ac
Under some circumstances building with depackers disabled was
failing. This should make the flag parsing more robust.
> build: better handling of no depackers configuration flag

- test-dev/Makefile.in
This adds `$(LDFLAGS)` to the test-dev linking rules that were missing it (`libxmp-tests`, `gen_mixer_data`, and `gen_module_data`). I kept running into issues with this because I've been building with ASan by using `CFLAGS=-fsanitize=address LDFLAGS=-fsanitize=address ./configure` and the lack of `$(LDFLAGS)` on the `libxmp-tests` rule prevents it from linking correctly.
edit: placing `$(LDFLAGS)` after `-o $@` was for consistency with `libxmp-covertest` but I don't really like that and it can be moved to right after `$(LD)` if that's preferable.
> Add LDFLAGS to libxmp-tests and utilities rules.

- src/loaders/dmf_load.c
X-Tracker modules can have up to 512 rows in a pattern. This is the only remaining pattern length limit issue I found in #197.  Unfortunately, this patch doesn't do anything to fix whatever other issues X-Tracker support has, so this loader is still disabled.
Fixes #197.
> Allow up to 512 rows in X-Tracker patterns.

- docs/libxmp.rst
warning started after the const return change for xmp_get_format_list()
> fix 'Title underline too short' warning from rst2html

- src/loaders/common.c
- src/loaders/loader.h
- src/loaders/mod_load.c
- src/loaders/ssmt_load.c
- src/loaders/stm_load.c
This adds a check to the code that generates ProTracker song sample filenames to make sure there isn't anything suspicious like slashes or ".." (as requested in the comments for https://github.com/cmatsuoka/libxmp/pull/116). I'm reasonably sure this patch is correct but I don't actually have any ProTracker song files to test this with right now, so please don't merge it. edit: I have tested it with a ProTracker song file now, so if you think the behavior of this new function is reasonable, I am OK with it being merged.
edit: also found this being used in the MTP loader, which currently isn't used, but I added this check to it anyway.
> Check ProTracker song file sample names before opening them.

- src/loaders/common.c
Fixes an amateurish mistake I added in #180 that thankfully MemorySanitizer caught. ;-(
This is the only MemorySanitizer issue I found locally with test-dev.
> Fix uninitialized read in libxmp_copy_name_for_fopen.

- .travis.yml
- test/Makefile
~~Just testing the Travis CI sanitizer checks again now that some legitimate issues (and a bunch of false positive spam) have been cleared up. Not expecting anything useful, but...~~ The Travis sanitizer checks work now and I've uncommented them. The last remaining issue in the way of this was a missing `$(LDFLAGS)` in the test Makefile.
Failed attempt 1: https://travis-ci.org/github/libxmp/libxmp/builds/743103830
Both sanitizers passing (verbose): https://travis-ci.org/github/libxmp/libxmp/builds/743117465
> Enable Travis CI clang sanitizer checks.

- Makefile.in
- configure.ac
- lite/Makefile.in.in
based on SDL configury.  move Darwin -Wl,-undefined,error to configure
for consistency.
> configure.ac: add -Wl,--no-undefined to LDFLAGS if supported.

- configure.ac
- test/test.c
It appears that `--no-undefined` is completely broken when trying to use the sanitizers with clang. I added a check to configure.ac to test for `fsanitize` before trying to add it. (I tried putting various programs in the `AC_TRY_LINK` prior to this but none of them flagged the same issue, probably because it only happens when linking a library.)
This should hopefully fix the new Travis sanitizer issues.
> Don't use --no-undefined when linking with -fsanitize.

- .travis.yml
- Makefile.vc
- Makefile.vc.in
- lite/Makefile.vc.in
Experimental Windows build on Travis. Documentation is a bit scarce, so
this was written on a trial-and-error basis. Variable substitution and directory
separator slashes/backslashes doesn't seem to work like in regular bash.
Clang sanitizer builds disabled because they failed consistently.
> build: add experimental travis windows build

- src/read_event.c
This patch makes the MOD, ST3, MED, and SMIX read_event functions ignore invalid note values instead of handling them as new notes. The prior behavior could allow out-of-bounds reads from the instrument keymap in these functions. No changes are required for the FT2 and IT read_event functions since they already check this.
Fixes #118. I will add a test for this when I get a chance.
> Fix read_event.c out-of-bounds reads due to invalid key values.

- src/loaders/dbm_load.c
DigiBooster Pro modules support fine volume slide and portamento but the quirk to enable that wasn't set in the DigiBooster Pro loader. This fixes multiple instances of loud notes in "Krashan - The Call of Quantum Field.dbm" caused by `AF1` being interpreted as a slide up instead of as a fine slide down (reported in #196).
> Enable fine effects for DigiBooster Pro modules.

- src/loaders/gdm_load.c
Adds an extended GDM effect I missed when fixing support for the fine slides. None of the other special extended GDM effects in the MenTaLguY documentation are actually implemented in BWSB, so I think that should be every GDM effect working now.
Test S3M and its converted GDM: [s3m_pan.zip](https://github.com/libxmp/libxmp/files/5551981/s3m_pan.zip)
> Fix GDM set pan position effect.

- docs/Changelog
- docs/libxmp.rst
- include/xmp.h
- libxmp.map
- lite/Changelog
- src/load.c
- test-dev/Makefile.in
- test-dev/test_api_test_module_from_file.c
- test-dev/test_api_test_module_from_memory.c
Adds new xmp_test_module variant functions for use in conjunction with `xmp_load_module_from_memory` and `xmp_load_module_from_file`. Identical to #134 by @Ghabry but with some cleanup of duplicate code, an unused variable removed, and some other tweaks.
> Add xmp_test_module_from_memory and xmp_test_module_from_file.

- README
- docs/libxmp.rst
- docs/manpage-header.rst
- lite/README
- lite/configure.ac
- lite/test/test.c
- src/load.c
- src/loaders/prowizard/prowiz.c
- load.c (load_module): remove empty if construct from hio_error()
when clearing error flag.
- prowiz.c (pw_wizardry): ditto.
- lite/test.c: release module and free context upon exit.
- lite/configure.ac: apply clang -fsanitize/--no-undefined patch to lite, too.
- README: change version to 4.5.
- lite/README: extend copyright years to 2020.
- docs/manpage-header.rst: change version to 4.5 and date to 2020.
- docs/libxmp.rst: whitespace fixes.
> minor adjustments for 4.5.0:

- docs/formats.txt
- src/loaders/gdm_load.c
This format is called "General Digital Music" but it was incorrectly named in the formats list and in the loader.
Sources:
* [GDMFORM.TXT](https://github.com/libxmp/libxmp/files/5609681/GDMFORM.TXT) packaged with Bells, Whistles, and Sound Boards.
* [MenTaLguY GDM format documentation.](https://github.com/libxmp/libxmp/blob/master/docs/formats/gdm.txt)
* [15 lines above the loader struct...](https://github.com/libxmp/libxmp/blob/master/src/loaders/gdm_load.c#L24)
(I've also seen it referred to as "General DigiMusic" before, but not in any official source...)
> Fix GDM format name ('General Digital Music', not 'Generic').

- .github/workflows/dist-package.yaml
Add a github action to build regular and lite distribution packages and
verify if they're correct.
> github/workflows: add distribution package test

- include/xmp.h
- src/common.h
- src/control.c
I made this fix at 27'th September 2019 while experimenting
with the Emscripten thing. Unfortunately, external variables don't like
the given export flag. Also, the build fails when emscripten.h wasn't included.
> Emscripten build fix

- src/common.h
- src/loaders/669_load.c
- src/loaders/far_load.c
- src/loaders/imf_load.c
- src/loaders/it_load.c
- src/loaders/liq_load.c
- src/loaders/no_load.c
- src/loaders/okt_load.c
- src/loaders/s3m_load.c
- src/loaders/stx_load.c
Fixes some more loader effects bounding issues found in the comments of #247, specifically out-of-bounds reads in `liq_load.c` and `imf_load.c`. I also added added explicit array sizes for most loaders using effects arrays (since in these loaders the array size is a functional part of the loader) and an `ARRAY_SIZE` macro so the relationship between the bounding and the effects array size is more obvious.
I'm not very familiar with Liquid Tracker or Imago Orpheus so if @debrouxl could verify that these loaders are correctly patched now that would be great.
> Fix effects array bounding in LIQ/IMF loaders.

- src/win32/debug.c
At my copy, I had to accidentally revert this fix I made a while ago, and the result was caused lots of missing `_D_` symbols in debug builds for MSVC 2015, 2017, and 2019. This happens in an attempt to link the static library to any building application.
> Fixed linking errors with debug builds at MSVC 2015, 2017, and 2019

- src/hmn_extras.c
- src/load.c
- src/loaders/fnk_load.c
- src/loaders/it_load.c
- src/loaders/mdl_load.c
- src/loaders/med4_load.c
- src/loaders/mtm_load.c
- src/loaders/prowizard/di.c
- src/loaders/prowizard/pha.c
- src/loaders/prowizard/tp3.c
- src/loaders/psm_load.c
- src/loaders/ult_load.c
- src/med_extras.c
- test-dev/test_api_load_module.c
Fixes the following bugs found in #251:
* The FNK loader could attempt to load more than 128 patterns despite having a fixed maximum pattern count of 128.
* The IT loader allows duplicate check actions in the range 0 to 3 but the array to convert DCAs to NNAs was only size 3.
* The MDL loader was missing checks to prevent loading modules with duplicate chunks.
* The MED4 loader could attempt to load instrument names of up to length 255 into an array of size 40.
* The MTM loader could attempt to load more than 32 channels despite having a fixed maximum channel count of 32.
* The PSM loader allows up to 255 samples but the sample offsets array was only size 64.
* The ULT loader was missing bounds checks on the channel count and track RLE unpacking.
* The ProWizard DI, Pha, and TP2/3 …
> Fix misc. fuzzing crashes.

- .gitignore
Updates the .gitignore file to ignore some miscellaneous files that were laying around my local repository being detected as untracked:
* config.cache
* test-dev/.read_test (not sure how this isn't getting unlinked, oh well)
* test-dev/all_tests.c (.gitignore rule had this in test/)
* test-dev/write_test (.gitignore rule had this in test/)
> Update .gitignore to ignore config.cache, test-dev misc. files.

- configure.ac
- lite/configure.ac
also some whitespace fixes.
(run `git diff -w` to see changes without whitespace changes.)
The only remaining warning from autoconf-2.70 is this:
`configure.ac:191: warning: AC_C_BIGENDIAN should be used with AC_CONFIG_HEADERS`
That is because AC_C_BIGENDIAN actually outputs this into config.h:
```
#if defined AC_APPLE_UNIVERSAL_BUILD
#else
#endif
```
i.e. it takes apple universal builds into account. However, if we start
using config.h, it will mean adding HAVE_CONFIG_H ifdefs into every *.c
file, therefore I didn't do AC_CONFIG_HEADERS.
> configure.ac: update to eliminate autoconf-2.70 warnings

- src/control.c
- src/mixer.c
- src/player.c
- src/smix.c
- src/virtual.c
When any pointer in the xmp_context data structures is freed it should now be cleared afterward to prevent potential double free issues (found most recently in #274 but also in other places before). Also, `module_data::instrument_path` now gets freed when a context is destroyed instead of leaking.
The only thing I noticed that might need to be patched but I did not patch here was that no pointers are ever cleared after freeing in fmopl.c, which could easily cause double free issues if e.g. `OPLCloseTable` is called twice or if `OPLCloseTable` is called after a failed `OPLOpenTable`. As far as I know currently all libxmp OPL code is dead and I don't know if there are any plans to restore it (and if there are, it may be worth considering replacing fmopl.c with Nuked OPL3).
> NULL pointers that may be reused after they are freed.

- docs/libxmp.rst
- src/control.c
- fixes XMP_MAX_FRAMESIZE sanity check.
- adds documentation for it
Closes #276.
> xmp_set_tempo_factor fix

- src/loaders/it_load.c
> it_load: handle cases where name field of header is not nul-terminated.

- docs/Makefile
- docs/style.css
The SourceForge version of the docs had a style.css linked within it. This recovers that stylesheet and embeds it into the generated html doc.
> Add style.css into html docs generation. 

- .github/workflows/dist-package.yaml
- .github/workflows/emscripten.yaml
The GitHub dist-package check has been failing on my fork branches due to a 404 error when attempting to download the package `python-pil`. The "fix" is to just run `sudo apt update` before attempting to install any packages. I also added this to the emscripten check even though it wasn't having this issue.
edit: [example failed check](https://github.com/AliceLR/libxmp/runs/1745452638).
> Fix dist-package check fails due to missing python-pil package.

- docs/Changelog
Using the ISO-8859-15 causes problem in several text editors and code viewers because of clunky nature of ANSI charsets system which are depending on computer locales
> Convert the docs/Changelog into UTF-8

- .gitignore
When do build the lite version, there is a lot of junk getting appears in the git status. Maybe do ignore that?
> Ignore files and directories generated by the lite build

- docs/formats/upkg.txt
- src/loaders/umx_load.c
... instead of linear search.
Similar versions are in libmikmod and libmodplug. For the
upkg parser code, see:  https://github.com/sezero/umr.git
> rewrite umx loader to use the embedded offset, size and object type

- src/depackers/arcfs.c
- src/depackers/oxm.c
- src/depackers/unzip.c
- src/load.c
- src/loaders/mmd_common.c
- src/loaders/prowizard/heatseek.c
Small set of patches fixing _some_ of the memory leaks / integer overflows
reported at https://github.com/libxmp/libxmp/issues/312
> bug #312 fixes

- src/mkstemp.c
for whatever reason, mingw-w64 defines pid_t as __int64 for WIN64,
but getpid() always returns int.
> mkstemp: don't use pid_t for windows builds.

- .gitignore
- test-dev/Makefile.in
- test-dev/Makefile.vc.in
- test-dev/main.c
This reduces the time it takes to run libxmp-tests.exe in my local MSYS2 setup from ~15 seconds to about 7 seconds. Considering how much I have been running the tests locally, this is a huge improvement. Presumably this will also be useful for adapting the tests to Visual Studio (#222). Thanks to Lionel Debroux for bringing the _spawn* family of functions to my attention. :)
(Suggestions for improving this are definitely welcome. The _spawn* functions apparently have existed since ~1993 and should be fairly portable.)
> Use _spawnl() for unit tests on Windows, add unit test Makefile.vc.in.

- docs/libxmp.rst
- src/hio.c
- src/load.c
- src/loaders/sample.c
- src/memio.c
- test-dev/test_read_mem_hio_nosize.c
- return -XMP_ERROR_INVALID from xmp_load_module_from_memory() and
xmp_test_module_from_memory() if size <= 0, remove all mention of
size <= 0 from their documentation.
- remove non-positive sizes support from memio.c. whitespace tidy-ups.
- remove hio_size() <= 0 check from load.c::set_md5sum()
- remove file_len >= 0 checks from sample.c::libxmp_load_sample()
- document that the size parameter to xmp_load_module_from_file() is
actually ignored. (don't know whether it had ever mattered..)
- change test_read_mem_hio_nosize so its tests always fail
Fixes: https://github.com/libxmp/libxmp/issues/325
Notes: hio.c::hio_open_file() doesn't fail if get_size() returns
negative: needs further check / handling.
> remove support for size <= 0:

- lite/test/test.c
Without this change, `make check` would fail.
> Apply commit ce19d177c8 to libxmp-lite

- docs/libxmp.rst
I didn't get this very minor documentation fix into #362 before it got merged. :)
> xmp_*_module_from_callbacks documentation tweaks.

- src/loaders/iff.c
Another minor tidying patch. Most of the -Wstringop-truncation warnings in libxmp were fixed by #179, but the `strncpy` in iff.c had to be reverted in #184 because, for a change, it's actually being used the way it was intended. GCC has been complaining about it since, though, and the simplest non-breaking fix seems to be to just expand the buffer size so it can be terminated. Not that it matters much, but this is a slight size increase for `iff_info` for 32-bit machines and was existing padding for 64-bit.
With this patch, neither GCC 10 nor GCC 11 emits any warnings on my end during the libxmp build process. :)
> Fix GCC warning in iff.c due to (correct) strncpy usage.

- src/common.h
- src/depackers/xz.h
- src/depackers/xz_config.h
- src/depackers/xz_dec_lzma2.c
- src/depackers/xz_dec_stream.c
- src/depackers/xz_lzma2.h
- src/depackers/xz_private.h
- src/depackers/xz_stream.h
- src/hio.h
- src/med_extras.c
This patchset greatly reduces the number of errors from c++ compilers.
The normal C builds are not affected - e.g. the watcom-built os/2 dlls
before and after this patchset are identical.
> misc cleanups / tidy-ups:

- test-dev/test_depack_rar.c
These functions should always be called in this test, not just when opening the module succeeds. Not sure why I thought this was correct, but ASan errors for this test in my Fedora VM (where `unrar` is not available).
> Fix missing free in test_depack_rar.c when unrar is missing.

- src/control.c
- test-dev/test_api_set_position.c
- test-dev/test_api_set_row.c
`xmp_set_position` allows setting the current order to an IT end marker, but `xmp_set_row` was missing safety checks for this situation.
> Fix crash when xmp_set_row is used on an IT end marker.

- src/loaders/it.h
- src/loaders/it_load.c
- src/loaders/itsex.c
- test-dev/test_depack_it_sample_16bit.c
- test-dev/test_depack_it_sample_8bit.c
This should fix a warning that occurs when building the regression tests with -flto (and is a better practice than leaving declarations everywhere).
> Move IT sample decompression declarations to it.h.

- test-dev/Makefile.in
Split from #398. The utility `gen_module_data` fails to link due to `util.o` depending on `hio.o`. This regression was introduced by #388.
> Fix linking for gen_module_data utility.

- configure.ac
- lite/configure.ac
- src/common.h
- src/control.c
e.g. with gcc >= 10.
Co-authored-by: Claudio Matsuoka
Closes: https://github.com/libxmp/libxmp/issues/385
> use the symver attribute, if available, for versioned symbols,

- src/depackers/mmcmp.c
- src/depackers/uncompress.c
- src/load.c
- src/loaders/amf_load.c
- src/loaders/common.c
- src/loaders/it_load.c
- src/loaders/mdl_load.c
- src/loaders/med4_load.c
- src/loaders/mfp_load.c
- src/loaders/prowizard/heatseek.c
- src/loaders/prowizard/mp.c
- src/loaders/prowizard/np3.c
- src/loaders/prowizard/p61a.c
- src/loaders/prowizard/tp1.c
- src/loaders/sample.c
- src/loaders/sym_load.c
- src/mixer.c
- src/player.c
- src/read_event.c
- src/scan.c
This fixes many `-Wshadow` warnings from gcc:
```
src/read_event.c: In function 'read_event_ft2':
src/read_event.c:460:30: warning: declaration of 'sub' shadows a previous local
src/read_event.c:389:28: warning: shadowed declaration is here
src/read_event.c:467:9: warning: declaration of 'p' shadows a previous local
src/read_event.c:384:22: warning: shadowed declaration is here
src/read_event.c:522:30: warning: declaration of 'sub' shadows a previous local
src/read_event.c:389:28: warning: shadowed declaration is here
src/read_event.c:533:9: warning: declaration of 'p' shadows a previous local
src/read_event.c:384:22: warning: shadowed declaration is here
src/scan.c: In function 'scan_module':
src/scan.c:76:6: warning: declaration of 'pat' shadows a previous local
src/scan.c:65:12: …
```
> fix several -Wshadow warnings.

- configure.ac
- libxmp.pc.in
- lite/configure.ac
- lite/libxmp-lite.pc.in
- configure.ac: updated list from libtool to filter systems that don't
have libm, or don't need it.
- libxmp.pc.in: add -lm to Libs.private only if present (or needed)
> update configuration for libm dependency:

- src/loaders/med2_load.c
- test-dev/test_loader_med2.c
This is a bandaid fix for the MED2 test failing for some setups: when the instrument path doesn't work (usually due to being relative), the MED2 loader now allows loading samples from the current module directory. I don't think this is how MED2 is supposed to work but IMO it's a reasonable way to distribute MED2 modules and it's how other song files are handled by libxmp.
Should fix #414, but we'll see.
> Allow loading MED2 samples from the module directory.

- src/common.h
- src/control.c
- src/format.h
- src/load.c
- src/load_helpers.c
- src/loaders/common.c
- src/loaders/it.h
- src/loaders/it_load.c
- src/loaders/loader.h
- src/loaders/mod.h
- src/loaders/s3m.h
- src/loaders/s3m_load.c
- src/loaders/sample.c
- src/loaders/xm.h
- src/loaders/xm_load.c
- src/memio.c
- src/mix_all.c
- src/player.c
- src/scan.c
- src/smix.c
- src/virtual.c
Hello! I maintain a shallow fork of libxmp-lite as a built-in library of a project of mine.
In order to compile properly in my project, my fork has had several tweaks and fixes applied to it. Most notably, it is able to compile as valid C++. I figured it would benefit both of us if these modifications were upstreamed: that way, the codebase is made more robust and portable, and I don't have to reapply so many modifications whenever I update my project's copy of the library.
Unfortunately, these modifications _only_ extend to libxmp-lite: my fork isn't based on the regular libxmp, so these changes won't make the entire libxmp library valid C++ nor will it address all of libxmp's uses of absolute include paths.
Hopefully someone more familiar with libxmp than me can apply my modifications …
> Make libxmp-lite valid C++ (also minor fixes)

- src/depackers/ppdepack.c
- src/depackers/s404_dec.c
- src/depackers/unarc.c
- src/depackers/xfd.c
Minor cleanup for the patches referenced in #442: these files no longer need to include `sys/stat.h`.
> Remove unused sys/stat.h includes in depackers.

- src/depackers/vorbis.c
src/depackers/vorbis.c: In function 'go_to_page_before':
src/depackers/vorbis.c:4791: warning: passing argument 2 of 'vorbis_find_page' from incompatible pointer type
src/depackers/vorbis.c: In function 'stb_vorbis_stream_length_in_samples':
src/depackers/vorbis.c:5077: warning: passing argument 2 of 'vorbis_find_page' from incompatible pointer type
src/depackers/vorbis.c:5077: warning: passing argument 3 of 'vorbis_find_page' from incompatible pointer type
src/depackers/vorbis.c:5092: warning: passing argument 2 of 'vorbis_find_page' from incompatible pointer type
src/depackers/vorbis.c:5092: warning: passing argument 3 of 'vorbis_find_page' from incompatible pointer type
> vorbis: fix warnings for targets where uint32_t is an unsigned long

- Makefile.vc
- Makefile.vc.in
- lite/Makefile.vc.in
- lite/src/loaders/mod_load.c
- src/common.h
- src/depackers/bunzip2.c
- src/list.h
- src/loaders/common.c
- src/loaders/masi_load.c
- src/loaders/med2_load.c
- src/loaders/mfp_load.c
- src/loaders/mod_load.c
- src/loaders/stm_load.c
- src/mdataio.h
- src/tempfile.c
- src/virtual.c
- test-dev/Makefile.in
- test-dev/Makefile.vc
- test-dev/Makefile.vc.in
- vc/libxmp.vcproj.in
- change libxmp_check_filename_case to call libxmp_get_filetype
for case-insensitive targets - removes all of target-specific
ifdef dance from common.c.  filetype.o added to TEST_INTERNAL
in test-dev to satisfy the libxmp_get_filetype dependency() of
common.o.
- add XMP_MAXPATH, default to _MAX_PATH for MSVC and Watcom, to
PATH_MAX if it's defined, to 1024 if not.  change all uses of
PATH_MAX to XMP_MAXPATH.
- common.h now includes limit.h for PATH_MAX: remove individual
limits.h includes. remove the only-two-remaining nacl-specific
sys/syslimits.h includes.
- simplify the __inline define in list.h.
- move /Dinline=__inline from VC makefiles to common.h for MSVC
- fix 'make check' in lite/Makefile.vc.
- properly clean test/* binaries in Makefile.vc.
> target-specific code / define clean-ups:

- test-dev/compare_mixer_data.c
- test-dev/configure.ac
- test-dev/main.c
- test-dev/test.h
- test-dev/util.c
- test/test.c
zeroes  >=330 kb of warning output from my gcc.
> added -Wall -Wwrite-strings to test-dev CFLAGS and fixed warnings.

- src/load.c
- src/loaders/xm_load.c
- src/scan.c
See #400. Fixes the following issues that affected loader performance:
* The XM pattern loader no longer relies on integer division instructions and allocates a single pattern work buffer instead of a new one for every pattern.
* The track pointers for the current pattern are now cached during `scan_module`, significantly improving scan performance by avoiding pointer aliasing overhead.
* The MD5 sum performed in `load_module` is delayed until after several sanity checks. This is mainly intended to help fuzzing performance. (Patch by @debrouxl.)
The XM diff is a little messy, which could maybe be worked around with an indentation hack for now if that's preferable.
> XM and other misc. loading performance improvements.

- configure.ac
- lite/configure.ac
- src/common.h
Versioned symbols use requires symbols visilibity and GNU ld as linker,
which our configury checks for.  common.h has additional black-listing
against target OSs, like Android, Apple, etc:
- Apple: macOS uses its own non-GNU ld and is detected by configury, so
it is handled.
- Android: The blacklist should have been because jni/Android.mk is set
to produce a static library.  There is nothing else preventing it, so
the new configury doesn't blacklist it.
- Emscripten, BeOS, Atheos, mint: New configury manually blacklists them
to match original common.h, just in case.
- Win32, amiga: already filtered out by not having symbol visibility.
Differently: the new configury version enables the versioned symbols only
for shared libraries, not static.
Closes: …
> move USE_VERSIONED_SYMBOLS decision to configuration time:

- src/depackers/depacker.c
- test-dev/test_depack_rar.c
This variable was changed to an array but I missed fixing the Android check.
> Fix Android disable for external depackers.

- CMakeLists.txt
- cmake/libxmp-checks.cmake
- lite/CMakeLists.txt
- lite/libxmp-lite.pc.in
- Use GNUInstallDirs, replace hardcoded install destinations
with CMAKE_INSTALL_xxxDIR
- Generate and install libxmp.pc (bug #474)
- MSVC now outputs libxmp.dll as it should, not xmp.dll
- MSVC now outputs libxmp-static.lib not xmp-static.lib
- Tweak libxmp-lite.pc installdir
> cmake fixes and improvements:

- .github/workflows/regression.yaml
- Makefile.in
- Makefile.lite
- aclocal.m4
- autogen.sh
- configure.ac
- lite/Makefile.in.in
- lite/configure.ac
- m4/Makefile
- m4/ld.m4
extracted LT_PATH_LD and its dependencies with minor modifications
from libtool for use in libxmp and placed as m4/ld.m4, and with an
aclocal.m4 pointing to it.  generating the configure script is the
same as before, simply running 'autoconf' (and _not_ autoreconf .)
> use LT_PATH_LD to detect GNU ld, which uses compiler's ld program:

- src/loaders/s3m.h
- src/loaders/s3m_load.c
Found via running checks for #357. libxmp completely ignores the sample segment high byte in S3Ms, leading to large S3Ms sounding very bad.
[Blatant example](http://modland.com/pub/modules/Screamtracker%203/DJ%20Meas/sunday%20train%20ride.s3m), though ModLand has at least 39 of these (and Mod Archive probably has far more).
No test because I don't think Claudio would appreciate me adding a 2.5 MB module to the repository. :-)
> Fix >1MB S3M modules relying on the sample segment high byte.

- src/hio.c
- src/load.c
- src/loaders/mmd1_load.c
- src/loaders/mmd3_load.c
- src/loaders/prowizard/prowiz.c
See https://github.com/libxmp/libxmp/pull/493#discussion_r738902930. `hio_seek` doesn't clear the error flag (which also stores the `EOF` state), which makes it semantically different from `fseek`, which is guaranteed to clear the `EOF` state. The result is that hitting `EOF` followed by an `hio_seek` will result in `hio_eof` returning 0 and `hio_error` returning `EOF`.
The fix is to just clear the error state on a successful `hio_seek` if it's `EOF`.
> hio_seek should reset the HIO_HANDLE stream error status on success.

- INSTALL
- src/hio.c
- src/loaders/umx_load.c
1. umx_load.c: remove extern declarations of format loaders
since commit 79c801493, format.h has them already.
2. hio_open_mem: add missing NULL-check for the returned ptr from mopen().
3. add notes to INSTALL file about emscripten configuration and also cmake.
(see https://github.com/libxmp/libxmp/issues/467)
> miscellaneous small stuff

- Makefile.vc
- cmake/libxmp-sources.cmake
- lite/watcom.mif.in
- src/loaders/Makefile
- src/loaders/common.c
- src/loaders/loader.h
- src/loaders/med4_load.c
- src/loaders/vorbis.c
- src/loaders/vorbis.h
- src/period.c
- src/period.h
- watcom.mif
- watcom.mif.in
1. generate a map file from watcom builds.
2. remove asif.c from build:
It is only used by ssmt_load.c, which hasn't been built since commit 34354ab7
3. med4_load: remove global symbol MAX_CHANNELS
its use has been removed as of commit 246b7c7
4. disable alloc_pattern_tracks_long & schism_tracker_string in lite builds
5. disable the seek api in stb_vorbis for libxmp
Bound to the new STB_VORBIS_NO_SEEK_API define.
The rest of the libxmp-unused functions in stb_vorbis are:
stb_vorbis_get_info, stb_vorbis_get_error`, stb_vorbis_get_sample_offset,
stb_vorbis_get_samples_short, stb_vorbis_get_samples_short_interleaved,
and stb_vorbis_stream_length_in_seconds, which possibly aren't worth the
trouble.  (Also see: https://github.com/libxmp/libxmp/issues/481)
There are also other code-dead-to-lite …
> more miscellaneous stuff: dead code

- CMakeLists.txt
- lite/CMakeLists.txt
The Playstation Portable actually does not support building shared libraries. We currently build with ``BUILD_SHARED=OFF``, but it would be nice if we didn't need to set that.
> Disable building shared for PSP by default

- src/depackers/mmcmp.c
MMCMP literal blocks were being output to wherever the last position in the file was instead of where their sub-blocks indicated they should be output. Introduced by this commit: https://github.com/libxmp/libxmp/commit/a679ac85f4340ad2bfd7ef50e772ed644d129bc7
> Fix MMCMP literal block unpacking.

- src/depackers/unxz.c
- src/depackers/xz.h
- src/depackers/xz_config.h
- src/depackers/xz_dec_lzma2.c
- src/depackers/xz_dec_stream.c
- src/depackers/xz_lzma2.h
- src/depackers/xz_stream.h
Since unxz.c was LGPL and didn't support extracting to a buffer, I went ahead and rewrote it to address both issues.
I also updated XZ Embedded to the latest version, but there's not a whole lot different: CRC-64 support we don't really care about, a small handful of minor(?) bugfixes, and some commenting. I reverted some stylistic changes to be closer to their original counterparts (like the CRC function names), but left everything that looked like a portability hack.
Some extra testing should be done on this before it's merged.
> Replace unxz.c with an MIT reimplementation, update XZ Embedded.

- src/loaders/umx_load.c
- replace strcasecmp use with a more universally available solution.
- don't overzealously restrict the loader to known upkg versions.
> minor updates to umx loader:

- .github/workflows/regression.yaml
Improvements for the GitHub Actions regression tests workflow:
* Replaced `make devcheck` with `(cd test-dev && make -j 3)` for Autotools targets (`-j 4` for Mac). The recursive make wasn't really necessary and was potentially actually harmful for MSYS2, where recursive makes invocations can be REALLY slow. This saves between a quarter and a half of the time that was previously being spent building the regression tests, which was also quite a bit in MSYS2.
* Combined the MSYS2 Autotools/CMake workflows. The vast majority of time spent in these is installing MSYS2 and dependencies (usually around 3 minutes), so these aren't much slower for being combined. The above patch offsets this a bit as well. Having these separate wasted a couple of our limited number of allowed actions and also …
> Combine MSYS2 regression tests, build test-dev with make -j#.

- src/depackers/arcfs.c
- src/depackers/bunzip2.c
- src/depackers/depacker.c
- src/depackers/depacker.h
- src/depackers/gunzip.c
- src/depackers/miniz.c
- src/depackers/mmcmp.c
- src/depackers/muse.c
- src/depackers/ppdepack.c
- src/depackers/s404_dec.c
- src/depackers/unarc.c
- src/depackers/uncompress.c
- src/depackers/unlha.c
- src/depackers/unlzx.c
- src/depackers/unsqsh.c
- src/depackers/unxz.c
- src/depackers/unzip.c
- src/depackers/xfd.c
- src/hio.c
- src/hio.h
- src/load.c
- src/memio.c
- src/memio.h
- test-dev/test_read_mem_hio.c
- test-dev/test_read_mem_hio_nosize.c
This affects the ppdepack, s404, sqsh, muse, zip, gzip, arc and arcfs depackers. The rest still require a temporary file for now.
TODO:
> Allow certain depackers to work without using a temporary file

- .github/workflows/regression.yaml
This is something I've seen in clang on Fedora, and it should have occurred to me before: parallel builds cause clang (newer versions only?) to occasionally catastrophically fail specifically when building test-dev. Reverting the macOS portion of #525.
> Revert parallel builds for macOS workflow test-dev build.

- .github/workflows/regression.yaml
Since libxmp contains Amiga-specific code, it's useful to be able to have Amiga builds in CI. This uses the [amigadev/crosstools](https://hub.docker.com/r/amigadev/crosstools) Docker images.
> Add AmigaOS 4 and MorphOS builds to GitHub Actions

- src/mixer.c
There is a `NULL` check for `vi->sptr` before mixing sample data but I forgot to add one before initializing the sample wraparound data. (Found thanks to Win32 text mode `stdout` mangling the module from test-dev/data/arcfsdata.)
> Fix mixer crash from not checking sptr before wraparound init.

- src/depackers/miniz_zip.c
Original libxmp report: https://github.com/libxmp/libxmp/pull/527
See upstream issue: https://github.com/richgel999/miniz/issues/218
> miniz_zip: fix mz_zip_reader_extract_to_heap to read correct sizes

- docs/formats.txt
As mentioned in a few issues (e.g. https://github.com/libxmp/libxmp/issues/460#issuecomment-898948675), fmopl.c is dead code and the AdLib formats are not currently supported.
> Remove AdLib/OPL formats from formats.txt

- src/filetype.c
src/filetype.c: In function 'libxmp_get_filetype':
src/filetype.c:102: warning: 'Examine' is deprecated (declared at interfaces/dos.h:92)
@raziel-, @bszili: This is correct, yes?
> filetype.c, amigaos4: eliminate use of deprecated calls:

- lite/watcom.mif.in
- src/depackers/miniz_zip.c
- src/depackers/xz.h
- src/loaders/digi_load.c
- src/loaders/imf_load.c
- src/loaders/mod_load.c
- src/loaders/stx_load.c
- src/loaders/vorbis.c
- src/mixer.c
- watcom.mif
- watcom.mif.in
This stupid PR is a result after my stupid attempts at building libxmp
with vbcc, which is capable of emiting really annoying warnings. After
this patchset it still emits only a few warnings (from imported sources
i.e. miniz_zip and vorbis), and the build actually fails because I can
not find a way around the missing `alloca` support in vorbis.c (I first
attempted using C99 VLAs but failed doing so - I possibly haven't tried
hard enough.)
Anyways, here it is.
> miscellaneous clean-ups

- cmake/libxmp-checks.cmake
- configure.ac
- src/loaders/vorbis.c
Alternative patch to #551: instead of using `alloca` or a VLA, this patch instead uses a temporary memory bound that stb_vorbis *already calculated* to `setup_malloc` a correctly-sized work buffer for `inverse_mdct` and `decode_residue`.
I'm going to fuzz it a little bit just to be sure the bound isn't missing anything.
> Replace alloca() usage in stb_vorbis with setup_malloc().

- CMakeLists.txt
- docs/CMakeLists.txt
- docs/Makefile
- docs/libxmp.rst
- docs/manpage.rst
- docs/pdfdoc.rst
Also update docs distfiles so that style.css goes into the tarball.
Changed the existing docs build, where we maintain two headers i.e.
manpage.rst and pdfdoc.rst which include libxmp.rst, so the tricky
sed machinery is no longer needed.
Closes: https://github.com/libxmp/libxmp/issues/477
Please test and review. CC: @Wohlstand
> Make cmake build the documentation:

- src/depackers/bunzip2.c
- src/depackers/crc32.c
- src/depackers/crc32.h
As suggested in https://github.com/libxmp/libxmp/issues/387#issuecomment-1002548099, this updates the bzip2 depacker to use up to date 0BSD-licensed code from https://github.com/landley/toybox/blob/master/toys/other/bzcat.c
TODO:
> Update the bzip2 depacker code to a newer 0BSD-licensed version

- src/read_event.c
- src/smix.c
- test-dev/test_api_smix_play_instrument.c
- test-dev/test_api_smix_play_sample.c
Fixes #106. This needs better testing and is probably not 100% correct currently.
> Allow xmp_smix_play_* to play key off, cut, and fade events.

- .github/workflows/regression.yaml
- .gitignore
- test-dev/Makefile.in
Changes the test-dev Makefile .c.o rule to emit dependency files via `-MMD`, makes the test-dev Makefile include these, and explicitly makes all_tests.c a dependency of every test object (the lack of this was causing Clang to crash occasionally with parallel make invocations). This hasn't been tested with especially old GCC versions and I don't know if `-MMD` or `-MD` will be an issue for them.
Fixes #541.
> Fix test-dev dependency tracking and Clang parallel make crashes.

- src/depackers/gunzip.c
Change the source license from LGPL to MIT.
> depackers: relicense gunzip depacker

- src/common.h
KallistiOS is a (the?) Sega Dreamcast toolchain originally made by Dan Potter of Farandole Composer fame : ). It provides a header including all of the fixed width types libxmp defines in common.h, so common.h needs to include that instead of redefining them.
I didn't bother putting it in the list for `uint64`/`int64` even though it defines them—the definitions are identical. I can add that for futureproofing if preferable.
Note just using `sh-elf-gcc` won't work. `_arch_dreamcast` is added to the list of compiler flags by the wrappers `kos-cc` and `kos-c++`. There are no other identifying preprocessor defines as far as I can tell. This configuration seems to work just fine:
```shell
CC=kos-cc ./configure --host=sh-elf --prefix=/home/a/libxmp/kos-testing --disable-shared --enable-static …
```
> Include arch/types.h for KallistiOS.

- src/load_helpers.c
- src/loaders/dt_load.c
- src/loaders/liq_load.c
- src/loaders/pt3_load.c
- src/loaders/xm_load.c
Fixes #604.
Some trackers for formats that save BPM as a word do not bother to clamp BPMs from input files, allowing edge case modules with hex edited high BPMs to play back correctly. Known affected trackers: Fasttracker 2, Digital Tracker, Protracker 3.6. None of these actually allow BPMs this high in the UI. OpenMPT allows up to a maximum of 1000 BPM in XMs it saves, which means some actual modules rely on this behavior and libxmp needs to support it.
Liquid Tracker is the only other tracker format libxmp supports with a 16-bit BPM, but it clamps the input BPM to <=255. The SoundFX loader can produce BPMs higher than 255 but this looks like a maybe intentional design feature. Everything else appears to either set BPM through effects or loads it from a byte.
This makes the minimum tick …
> Increase BPM maximum to 1000 to fix edge case XMs/DTMs/PTMs.

- src/loaders/common.c
- src/loaders/loader.h
- src/loaders/st_load.c
This can be seen in files created using [TrackConv](http://web.archive.org/web/20021108131930/http://listen.to/qtm) on RISC OS.
> Support loading SoundTracker modules using CR terminators

- src/depackers/depacker.c
- src/depackers/depacker.h
- src/hio.c
- src/hio.h
- src/load.c
These new hio.c functions act as a combined `hio_close` + `hio_open_*` which does not free or allocate a new `HIO_HANDLE *`, allowing the depackers system and loaders (#586) to replace an `HIO_HANDLE *` without being passed a `HIO_HANDLE **`. This cleans up some ugly code in the depackers.
This could *probably* be improved further by making the `MFILE` and `CBFILE` part of `HIO_HANDLE` instead of separately allocating them, which would eliminate some error paths, but I don't think it's really necessary right now.
Also worth nothing that once the LHA, RAR, and MO3 depackers are replaced, `hio_reopen_file` can be removed.
> Add hio_reopen_* functions for #586.

- src/loaders/s3m_load.c
For a moment I thought about pulling the extended Schism Tracker version information into this PR as well (which is required for identifying Schism Tracker versions built after 2020-10-28), but then my brain froze looking at that code... Maybe later.
> Detect S3M files made with Graoumf Tracker, and use full OpenMPT version

- .gitignore
- test-dev/Makefile.in
- test-dev/configure.ac
- test-dev/libxmp_fuzz.c
This adds the option to build the libFuzzer test function as a standalone program with some minimal options and status output. The standalone version of the test function is essentially the same test program I've been using to test files by loading them into memory for a few years now.
Mainly this means I don't have to copy around that utility everywhere I set up libxmp, and I don't need to update its version of the fuzzing test to match the libxmp test when I change it. However, this might also be really useful for AFL++ or other fuzzers that execute a command line e.g. `./xmpchk -q -- [filename]`. (@debrouxl)
The program is located at `test-dev/xmpchk` and can be built with the test-dev target `make utilities` after libxmp has been built normally.
Examples:
```shell
./xmpchk -f8 …
```
> Add command line test utility based on the libFuzzer test function.

- libxmp-config.cmake
CMAKE_CURRENT_LIST_DIR is the proper name, reference: https://cmake.org/cmake/help/latest/variable/CMAKE_CURRENT_LIST_DIR.html
> Fix typo in CMake config

- src/common.h
- src/depackers/depacker.c
- src/depackers/ptpopen.c
- src/mkstemp.c
Fixes https://github.com/libxmp/libxmp/issues/642
This fix will work for all build systems.
CMake sets `-DWINAPI_FAMILY=WINAPI_FAMILY_APP` when building for UWP so there is a simpler fix but only if you don't care about other build systems.
> Fix compilation for UWP platform, disable external helpers

- src/loaders/it_load.c
- src/loaders/xm_load.c
- test-dev/data/format_xm_instsamples.data
Adds a small handful of MPT module detection improvements:
* ModPlug Tracker XMs are now detected in many (but not all) cases. This is currently used only to apply MPT preamp to XMs that expect it. Example: `test-dev/data/m/xyce-dans_la_rue.xm`.
* ModPlug Tracker XM comments are now loaded.
* IT modules *probably* saved using early ModPlug Tracker pre-alpha releases are now detected. These have tracker version `0202h`, format version `0200h`, an a non-zero first pattern parapointer that is less than the first sample parapointer. There are only a very small number of these on Modland, and this fingerprinting was only recently discovered by Saga Musix.
> Add tracker detection for ModPlug Tracker XMs, pre-alpha ITs.

- src/depackers/gunzip.c
- src/loaders/xmf_load.c
Their use lead to warnings in mingw debug builds:
```
D:/a/libxmp/libxmp/src/depackers/gunzip.c: In function 'decrunch_gzip':
D:/a/libxmp/libxmp/src/common.h:198:16: warning: unknown conversion type character 'z' in format [-Wformat=]
198 | #define D_CRIT "\x1b[31m"
|                ^~~~~~~~~~
D:/a/libxmp/libxmp/src/common.h:202:46: note: in definition of macro 'D_'
202 |                 __FILE__, __LINE__); printf (__VA_ARGS__); printf ("\x1b[0m\n"); \
|                                              ^~~~~~~~~~~
D:/a/libxmp/libxmp/src/depackers/gunzip.c:155:20: note: in expansion of macro 'D_CRIT'
155 |                 D_(D_CRIT "CRC-32 mismatch: expected %08zx, got %08zx",
|                    ^~~~~~
D:/a/libxmp/libxmp/src/common.h:198:16: warning: unknown conversion type character 'z' in …
```
> replace unnecessary use of %z in format-strings in D_().

- Makefile.lite
- autogen.sh
- test-dev/Makefile.in
- Makefile.lite: tweak DFILES:
Copy configure.ac and Makefile.in from the lite directory, not from
top-level. And remove configure script from DFILES: The rest of the
rules already run autoconf in the staging directory i.e. it will be
generated already.  No need to generate the configure script before
running Makefile.lite, anymore.
- autotools: allow specifying the autoconf command in AUTOCONF env. var.
(on the make command line in case of Makefile.lite.)
> minor Makefile.lite and autotools updates

- CMakeLists.txt
- lite/CMakeLists.txt
This fixes the following warning when configuring with CMake 3.27+:
```
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
Compatibility with CMake < 3.5 will be removed from a future version of
CMake.
Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.
```
@madebr: This was adapted from your SDL2 patch. OK?
> cmake: set maximum policy to 3.5

- test-dev/test_mixer_bidi_sync.c
Noticed by Thomas Neumann
Fixes: https://github.com/libxmp/libxmp/issues/681
> test_mixer_bidi_sync test: use the parameters to bidi_sync_test_mode()

- docs/Changelog
- src/scan.c
- test-dev/Makefile.in
- test-dev/all_tests.txt
- test-dev/test_player_loop.c
* "alien incident - leohou2.s3m" by Purple Motion had broken loop detection in sequence 8 due to it using a pattern jump to an end marker associated with sequence 7. Fixed by handling end markers in the scan regardless of which sequence they are attached to.
* "amazonas-dynomite mix.it" by Skaven had broken loop detection in sequence 9 caused by the scan placing its loop point inside of a nonexistent marker "pattern". Fixed by placing the loop point at the start of the first real pattern in a sequence.
> Fix loop detection edge cases broken by S3M/IT marker scan bugs.

- src/scan.c
This is a very simple PR. While profiling `scan_module`, I noticed that the effects slots for all events were compared to all possible FX, even though the vast majority of effects slots are empty.
The only change in the PR is to skip these checks if both effects slots for an event are empty.
In my benchmarking, this yields about a 10% load time improvement *in general*.
> scan.c: optimize for common case of no effects

- src/scan.c
- test-dev/test_player_loop.c
If two sequences jump to the same invalid/skip pattern immediately prior to the end of the module, the previous scan fix patch would attempt to read the order list out-of-bounds. I've fixed this by just making the invalid/skip pattern handling part of the same branch as the S3M_END handling in the fix, which I should have done anyway.
Found by libFuzzer.
> Fix an extra scan edge case related to scan edge case fix #688.

- src/loaders/iff.c
This line of code emits a warning when building with `-Wstrict-prototypes`. Found using emcc.
> Fix -Wstrict-prototypes warning in iff.c.

- docs/Changelog
- src/loaders/stm_load.c
All STMs should have 0x1a as their EOF byte, but two broken STM modules "putup10.stm" and "putup11.stm" have a value of 2 here instead. This patch allows those modules to load.
Fixes #700.
> Fix loading edge case STMs with an EOF byte of 2.

- src/loaders/vorbis.c
Patch by Seb de Graffenried (@Seb-degraff): https://github.com/nothings/stb/pull/1563
Fixes distorted decompressed audio when UBSan was enabled.
> Import an stb_vorbis fix from upstream PR/1563:

- src/loaders/vorbis.c
The following 4 patches are based on PR submissions at mainstream.
I modified most of the patches and notified the patch author about
them.
(1) Fix CVE-2023-45679 and CVE-2023-45680:
Based on the patches by Jaroslav Lobačevski (@JarLob) submitted
to mainstream at: nothings/stb#1557 and nothings/stb#1558
GHSL-2023-169/CVE-2023-45679: Attempt to free an uninitialized memory pointer in vorbis_deinit()
GHSL-2023-170/CVE-2023-45680: Null pointer dereference in vorbis_deinit()
(2) Fix CVE-2023-45681 (integer overflow):
Based on patch by Jaroslav Lobačevski (@JarLob) submitted to
mainstream at nothings/stb#1559
GHSL-2023-171/CVE-2023-45681: Out of bounds heap buffer write
(3) Fix CVE-2023-45676 and CVE-2023-45677 (integer overflow in setup_malloc()):
Based on the patches by Jaroslav Lobačevski …
> stb_vorbis CVE fixes

- src/depackers/depacker.c
A few ZIPs I have from an artist include HTML READMEs alongside their .diz files, which is preventing libxmp from detecting them properly.
> exclude_match: add HTML files

- configure.ac
- lite/configure.ac
I am by no means an autoconf/workingset master, but...
```config
VERSION_MAJOR	= @libxmp_VERSION_MAJOR@
VERSION_MINOR	= @libxmp_VERSION_MINOR@
VERSION_RELEASE	= @libxmp_VERSION_PATCH@
VERSION		= @libxmp_VERSION@
```
This was producing library links literally named like the following:
```
libxmp.so.@libxmp_VERSION_MAJOR@
libxmp.so.@libxmp_VERSION@
```
Now:
```
libxmp.so.4
libxmp.so.4.6.0
```
```sh
$ uname -srvmo
Linux 6.7.7-100.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Mar  1 16:51:49 UTC 2024 x86_64 GNU/Linux
$ autoconf --version | head -n 1
autoconf (GNU Autoconf) 2.71
```
Am I missing something?
https://www.gnu.org/software/autoconf/manual/autoconf-2.64/html_node/Setting-Output-Variables.html
> Fix config version variables.

- src/med_extras.c
- src/mixer.c
Fixes GCC's latest contribution to compiler warnings :) found while testing Fedora 40.
Note `XMP_MAX_FRAMESIZE` is the number of frames in the buffer, not the size of an individual frame in the buffer (hence I reversed both instances in mixer.c instead of just the one that triggered the warning).
```
CC src/med_extras.lo
src/med_extras.c: In function ‘libxmp_med_new_module_extras’:
src/med_extras.c:388:50: warning: ‘calloc’ sizes specified with ‘sizeof’ in the earlier argument and not in the later argument [-Wcalloc-transposed-args]
388 |         me->vol_table = (uint8 **) calloc(sizeof(uint8 *), mod->ins);
|                                                  ^~~~~
src/med_extras.c:388:50: note: earlier argument should specify number of elements, later size of each element …
```
> Fix GCC 14 -Wcalloc-transposed-args warnings.

- .github/workflows/regression.yaml
To fix `autoconf: command not found` errors.
From CI logs:
```
Run brew install autoconf cmake
Warning: Treating cmake as a formula. For the cask, use homebrew/cask/cmake or specify the `--cask` flag.
Warning: cmake 3.29.2 is already installed and up-to-date.
To reinstall 3.29.2, run:
brew reinstall cmake
==> Downloading https://ghcr.io/v2/homebrew/core/autoconf/manifests/2.72
==> Fetching dependencies for autoconf: m4
==> Downloading https://ghcr.io/v2/homebrew/core/m4/manifests/1.4.19
==> Fetching m4
==> Downloading https://ghcr.io/v2/homebrew/core/m4/blobs/sha256:f42d89db519a07d67bcaead6c8dfb2da45e8266bebb996dd8b3f19b1ca13b8a0
==> Fetching autoconf
==> Downloading https://ghcr.io/v2/homebrew/core/autoconf/blobs/sha256:bb39057e87dd9cb940bee15ff5b5172952a0350e59b14a6f55b8006a07813186
==> …
```
> CI, macOS: run 'brew install autoconf'

- src/common.h
- src/mkstemp.c
- src/tempfile.c
- test-dev/test.h
Defines in common.h to avoid MSVC C4996 warnings were defunct, because:
(i) dup, fileno, strnicmp, and S_ISDIR() aren't used anywhere, at least
not for windows, and:
(ii) the rest requires including io.h, and common.h used to be included
before it resulting in a mess.
Therefore, remove those defines from common.h, and define the necessary
ones only where they are needed, namely mkstemp.c and tempfile.c.
Also define `__MINGW_FEATURES__` as 0 if not already defined, in order to
avoid loud -Wundef warnings from old mingw.org headers.
> windows C4996 warning fixes and include tidy-ups :

- lite/test/CMakeLists.txt
- test/CMakeLists.txt
- ctest would fail in lite distribution,
- ctest would fail in full tree with depackers disabled.
> fix ctest regression in test/test.c after PR/721 merge :

- CMakeLists.txt
to match commit 1ff5c5a539e6497a27dfd998dfdebbcb708daff1 (was missed in PR/721)
> cmake: tweak openbsd detection in BUILD_LITE case.

- Makefile.vc
- cmake/libxmp-sources.cmake
- lite/src/Makefile
- src/Makefile
- src/common.h
- src/control.c
- src/lfo.c
- src/lite/Makefile
- src/lite/lite-rng.c
- src/loaders/flt_load.c
- src/read_event.c
- src/rng.c
- src/rng.h
- test-dev/CMakeLists.txt
- test-dev/Makefile.in
- test-dev/Makefile.vc
- test-dev/libxmp_fuzz.c
- test-dev/test_storlek_20_pan_swing_and_set_pan.c
- watcom.mif
This patch replaces all rand() usage with a built-in implementation of xorshift32. This is not an especially cryptographically good PRNG but it is fast (4 bitshifts, 3 XORs, 1 multiply for output) and produces reasonably "random" output.
Unlike rand(), this implementation is reentrant i.e. it easily supports multiple different concurrent states and doesn't cause any race conditions with caller code outside of libxmp.
This implementation will also behave exactly the same on all platforms given a fixed seed, which allows the fuzzer/xmpchk and the storlek_20.it test to use fixed seeds. (Lack of doing this has caused failures of this test on NetBSD and in neumatho's C# port.)
Fixes #685 and #723.
> Replace rand() with a built-in reentrant alternative.

- src/depackers/miniz_zip.h
- src/loaders/vorbis.c
- src/miniz.h
Was feeling more retro than usual: With this patch applied, I was able
to build libxmp using msvc 4.0 and 4.2, if you can believe it...
> conditionalize use of __forceinline

- Makefile.os2
- Makefile.vc
- Makefile.vc.in
- Makefile.w32
- lite/Makefile.os2
- lite/Makefile.vc.in
- lite/Makefile.w32
- lite/watcom.mif.in
- watcom.mif
- watcom.mif.in
avoids 'too long' errors on old operating systems.
P.S.: msvc makefile in test-dev is weird, I didn't touch it. If you want
I'll try and mess with it, or I can keep it as is because it works where
it matters.
> use response files with msvc and watcom makefiles.

- docs/Changelog
- lite/Changelog
- src/loaders/s3m_load.c
Also minor rearrangement in lite ChangeLog so that it diffs cleaner
against the full version.
Also update copyright years of s3m_load.c
P.S.: The lite <-> full changelog diff isn't clean in 4.5.0 section
I gave up immediately when I hit that part, better to leave as is..
> Update ChangeLog for 4.6.1 changes so far

- docs/Changelog
- docs/libxmp.rst
- lite/Changelog
- src/control.c
- src/mixer.c
- src/mixer.h
- test-dev/Makefile.in
- test-dev/all_tests.txt
- test-dev/test_api_set_tempo_factor.c
* `xmp_set_tempo_factor` now returns `-XMP_ERROR_STATE` when called prior to `xmp_start_player` (instead of causing crashes).
* Fix mixer crashes caused by previously valid tempo factors after sample rate or BPM changes.
If the new return value is too much of a problem for 4.6.1 I can change it to -1.
The crash is easily reproduceable by setting the time factor to some nonsense prior to calling `xmp_start_player` (`xmp_set_tempo_factor` will also generate an UndefinedBehaviorSanitizer error):
```C
int main(void)
{
xmp_context ctx = xmp_create_context();
xmp_load_module(ctx, "test-dev/data/test.it");
xmp_set_tempo_factor(ctx, 10000.0);
xmp_start_player(ctx, 44100, 0);
xmp_play_frame(ctx); // crash
xmp_free_context(ctx);
return 0;
}
```
> Fix crashes caused by xmp_set_tempo_factor.

- src/mix_all.c
- src/mixer.c
- src/mixer.h
* The interpolation macros now take an output sample and a sample number (required for stereo mixers for obvious reasons). The channel count is provided via a `const int` for lack of a better way of doing this (should not harm most builds). The alternative was yet another macro parameter to the interpolators and UPDATE_POS.
* Renamed the interpolation macros for consistency.
* I've separated the filter macros from the output macros since the filter macros are supposed to operate on the INPUT according to sagamusix. These macros take one or two input+output variables.
* The output macros have been greatly simplified, and now take one or two output variables.
* Similarly, the variable declarations needed an overhaul.
* Reverted 69653c24 as the underlying cause seems to have been fixed …
> Reformat mixer macros in preparation for stereo mixers.

- docs/libxmp.rst
`xmp_channel_mute` has another way of muting or unmuting that wasn't documented. 
Setting the status to 2 (or greater) will inverse the channel's current status.
> Update paramaters of xmp_channel_mute in libxmp.rst

- src/depackers/arc.c
- src/depackers/arcfs.c
- src/depackers/bunzip2.c
- src/depackers/depacker.c
- src/depackers/depacker.h
- src/depackers/gunzip.c
- src/depackers/lzx.c
- src/depackers/mmcmp.c
- src/depackers/ppdepack.c
- src/depackers/s404_dec.c
- src/depackers/uncompress.c
- src/depackers/unlha.c
- src/depackers/unsqsh.c
- src/depackers/unxz.c
- src/depackers/unzip.c
- src/depackers/xfd.c
This allows depackers to test the input stream directly rather than the 1k buffer that libxmp currently provides them, which will be useful for formats that don't provide a magic string at the start.
Example 1: Pack-Ice—a packer format used on the Atari ST and Falcon (and occasionally the Amiga?)—in the 1.x variant of its format writes a footer with a 4 byte signature at the end of the file. It is impossible to detect this variant otherwise. I am currently finishing a depacker for the Pack-Ice format because Digital Tracker natively loads the 2.3/2.4 variant of it (allegedly; unpacking seems broken prior to Digital Home Studio) and the author regularly used Pack-Ice 2.3/2.4 on their modules.
Example 2: Zip does not reliably contain a magic string at the start (our Zip depacker currently …
> Add depacker test_hio function for more complex packed formats.

- src/loaders/xm_load.c
Added an extra check on the restart value for XM modules, so it is possible to play "10 Days Of Abstinence.xm".
This module has a value of 0xffff as the restart and before this change, the loader failed. Now it can load this module and play it.
You can find the module here:
https://modland.com/pub/modules/Fasttracker%202/Andy%20(DE)/10%20days%20of%20abstinence.xm
> Added an extra check on the restart value for XM modules

- src/mix_all.c
```
src/mix_all.c:173:18: warning: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
173 |     register int smpl; \
|                  ^~~~
```
> mix_all.c: avoid -Wregister warning from c++ compilers:

- src/loaders/mod_load.c
- test-dev/data/format_mod_dt.data
Workaround for a bug caused by a change prior to version tracking. I should note that libxmp-lite is not setting the restart position for MOD anywhere whatsoever as far as I can tell.
Ideally it'd be nice to know why that line was commented out so it can be uncommented.
Fixes #763 for libxmp and  libxmp-lite.
> Fix restart position for >64k sample and Digital Tracker MODs.

- test-dev/Makefile.in
- test-dev/libxmp_fuzz.sh
The HWAddressSanitizer is very similar to AddressSanitizer except, instead of using redzones and a quarantine that consume a lot of RAM, it uses address tagging (via AArch64 top byte ignore) to detect out-of-bounds accesses and use-after-frees. This significantly reduces the RAM consumed, which has been a constant issue on my Le Potato.
I also reformatted the fuzzer rules yet again to hopefully suck less. Instead of making the fuzzer libraries interdependent to synchronize them, the fuzzer builds now use CMake with different build directories. The alternative was duplicating the copy source tree for each build. This was necessary because the new fuzzer (and potentially other future ones) are optional. Other considerations: .NOTPARALLEL doesn't work on individual rules in fairly recent …
> Add HWAddressSanitizer fuzzer (AArch64 only).

- test-dev/test_mixer_bidi_sync.c
Fixes #689. I just removed the single broken test case (XM, nearest, 8000Hz) as it inexplicably contains a pop 3/4 through that only seems to affect very low rates and doesn't otherwise break the test. Nearest passes at 11025Hz for both modules.
> Fix test_mixer_bidi_sync to test different interpolation modes.

- src/loaders/itsex.c
Fixes a bogus warning that I've found mainly when compiling libxmp with Debian 12 (but presumably affects other GCC versions and distros). This struct can never actually be used uninitialized, but some versions of GCC fail to recognize that regardless.
> Fix GCC 12(?) -Wmaybe-uninitialized in IT sample decompression.

- src/bitrot/loaders/ssmt_load.c
- src/loaders/common.c
- src/loaders/loader.h
- src/loaders/med2_load.c
- src/loaders/mod_load.c
- src/loaders/stm_load.c
I found a few glaring issues that needed addressing while fixing a MED2 loader snprintf truncation warning related to sample loading. The MOD, STM, MED2, and (bitrot) SSMT loaders all contain separate routines to generate the path of an instrument/sample file when loading song files. These are implemented roughly as follows:
* MOD: combine `m->dirname` with the cleaned sample name, open.
* STM: combine `m->dirname` with the cleaned sample name, open.
* SSMT: combine `m->dirname` with the cleaned sample name, open.
* MED2:
1) Get the instrument path set by `xmp_set_instrument_path` or if it is not set, get the environment variable `XMP_INSTRUMENT_PATH`, or if it is not set, `.`. Combine this with the cleaned sample name and attempt a case-insensitive match, then open.
2) Combine …
> Merge song file instrument path detection routines.

- Makefile.in
- lite/Makefile.in
Object build rules do reference CPPFLAGS, but CPPFLAGS hadn't
used to be populated in the makefile:  now it does.
> autotools: make CPPFLAGS actually matter

- docs/libxmp.rst
- src/control.c
- src/loaders/common.c
- test-dev/Makefile.in
- test-dev/all_tests.txt
- test-dev/test_api_set_instrument_path.c
The API function `xmp_set_instrument_path` crashes when provided with a path of `NULL` due to passing that `NULL` on to `libxmp_strdup`. I've fixed `libxmp_strdup` to return `NULL` when this occurs, and I've revised the behavior of `xmp_set_instrument_path` to clear the instrument path when given `NULL`. This is undefined behavior for `xmp_set_instrument_path` so it should not require a minor version change.
> Fix crash when calling xmp_set_instrument_path with NULL.

- CMakeLists.txt
- lite/CMakeLists.txt
compatibility with CMake < 3.10 will be removed in a future CMake version
( CC: @madebr )
> cmake: set maximum policy to 3.10

- src/effects.c
- src/scan.c
The fix from 70d98fc6, which changed IT pattern break to not be handled if a lower channel performed a loop, has also been applied to the scan. This fixes the reported duration of ZX_11.it (should be 1m14s, was reporting 1m11s).
[ZX_11.it.zip](https://github.com/user-attachments/files/18124416/ZX_11.it.zip)
> Apply fix from #99 to the module scan too.

- src/player.c
`player.c(593,1): warning C4701: potentially uninitialized local variable 'lps' used`
Old gcc versions also emit the same warning:
```
src/player.c: In function `update_invloop':
src/player.c:565: warning: `lps' might be used uninitialized in this function
```
The warning is bogus, though.
> player.c (): Fix MSVC C4701 (uninitialized local variable) warning:

- src/depackers/xz_dec_stream.c
- src/depackers/xz_stream.h
`depackers\xz_dec_stream.c(424,7): warning C4125: decimal digit terminates octal escape sequence`
> depackers, xz: Fix MSVC C4128 warning:

- src/loaders/sample.c
- test-dev/test_string_adjustment.c
`loaders\sample.c(134,16): warning C4310: cast truncates constant value`
`test-dev\test_string_adjustment.c(6,9): warning C4310: cast truncates constant value`
Closes: https://github.com/libxmp/libxmp/issues/797
> fix MSVC C4310 warnings:

- src/loaders/common.c
`src/loaders/common.c(473): Warning! W391: col(25) assignment found in boolean expression`
> silence W391 warning from Watcom C++:

- src/depackers/arc_unpack.c
```
depackers\arc_unpack.c(139,29): warning C4310: cast truncates constant value
depackers\arc_unpack.c(132,45): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
depackers\arc_unpack.c(740,14): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
```
Curiously ARC_NO_CODE and some other constants are marked with `UL` even though unnecessary, i.e. a simple `U` would have been fine w/o making them 64 bits on LP64. I didn't touch those.
> depackers, arc_unpack: silence MSVC C4310 and C4334 warnings

- src/common.h
- src/depackers/bunzip2.c
- src/loaders/sample.c
The warnings disabled are `signed/unsigned mismatch` for `<`, `<=`, `>`, `>=`, `==` and `!=`, and `conversion from 'type' to 'int', possible loss of data` stuff.
After this, combined with #801, there is one warning from MSVC that remain:
```
loaders\sample.c(75,12): warning C4245: '*=': conversion from 'int' to 'uint8', signed/unsigned mismatch
```
This is for `p[i] *= -1` where p is an `uint8*`: Anything to do?
> silence MSVC C4018, C4389, C4244 and C4267 warnings in all source tree

- cmake/libxmp-checks.cmake
- src/common.h
we're disabling them in common.h already
> cmake: remove disabling of MSVC warnings

- CMakeLists.txt
- lite/CMakeLists.txt
Fixes: https://github.com/libxmp/libxmp/issues/810
CC @madebr
> cmake: quote libxmp.map path in LINK_FLAGS for paths with spaces

- CMakeLists.txt
- configure.ac
- docs/Changelog
- docs/manpage.rst
- include/xmp.h
- lite/CMakeLists.txt
- lite/Changelog
- lite/configure.ac
- src/depackers/arc_unpack.c
- src/effects.c
- src/loaders/arch_load.c
- src/loaders/dbm_load.c
- src/loaders/mgt_load.c
- src/loaders/no_load.c
- src/loaders/rtm_load.c
also fix a minor 'unused label' warning in lite builds.
> bump version to 4.6.1, update changelogs, update copyright dates

- docs/Changelog
- src/player.c
Fixes Emax/enjoy the silence.mod channel 4. Skipping a test for this one since the current Invert Loop test is a mixer samples test and this would need a more comprehensive test.
You can verify the fix by listening to the aforementioned module with the option `-M0,1,2` and comparing to OpenMPT. Without the fix, channel 4 gradually shifts in timbre over the course of the entire module, but with the fix, its samples are modulated in a much more controlled manner: http://modland.com/pub/modules/Protracker/Emax/enjoy%20the%20silence.mod
Fixes #784.
> Reset Invert Loop position when a new instrument is encountered.

- src/common.h
Closes https://github.com/libxmp/libxmp/issues/373
> band-aid for AC_C_BIGENDIAN, because we aren't using autoheader.

- src/loaders/xm_load.c
The Four Ages.oxm module have a sample which is Ogg Vorbis packed. When depacking it, it result in a sample with 0 length. Because LibXmp check the result after depacking, which is the length of the depacked sample or negative if failed as <= 0, the load fails. This fix will make sure the module can be loaded correctly.
The realloc change is at least needed on Windows. If not, Xmp.exe just exit.
[Four Ages.zip](https://github.com/user-attachments/files/18288539/Four.Ages.zip)
> Empty sample in oxm modules

- src/miniz_tinfl.c
This reverts commit 4ec860304e2887b5d5855cdf9f649cf5cca7028f
Issues were reported to mainstream: https://github.com/richgel999/miniz/pull/329
I guess we wait and see whether we receive complaints.
Or, should we make an immediate patch release for this??
> Revert 'miniz_tinfl.c: apply CVE-2018-12913 fix from mainstream.'

- src/loaders/stm_load.c
When I scanned modland to check my own player, I discovered a lot of false positives for Scream Tracker 2. This fix will make them go away, by copying the version check from the load part into the test part as well.
Here is a list of some of the modules I found that created false positives. All from modland:
MegaStation MIDI\DJ Hikari\sss.msm
Piston Collage\12\obj1124-4.ptcop
Piston Collage\3-14\obj0667-1.ptcop
Piston Collage\Agaragara\011.ptcop
Piston Collage\Agaragara\obj0535-4.ptcop
Piston Collage\Bakushi\noname10.ptcop
Piston Collage\Canot\obj1365-1.ptcop
Piston Collage\CFZ\obj0266-1.ptcop
Piston Collage\Colo\obj0439-1.ptcop
Piston Collage\Colo\obj0556-1.ptcop
Piston Collage\Colo\obj0805-1.ptcop
Piston Collage\Colo\obj1051-1.ptcop
Piston Collage\Cthulhu\obj1182-1.ptcop
Piston …
> False positives in Scream Tracker 2

- src/loaders/it_load.c
When making a check for usage of DSP effects/VST plug-ins, I found out that some modules do have edit history but not midi configuration. Then the file pointer was at the wrong place when I needed to do my extra check.
Currently, it does not make any difference for Xmp, since it make a seek when loading instruments/samples. But if you want in the future to support some of the extra OpenMpt features, this fix will help :-)
An example module is Digital loop by Saga Musix (https://modland.com/pub/modules/Impulsetracker/Saga%20Musix/digital%20loop.it)
> Moved the check for edit history out of the midi configuration part

- src/loaders/xmf_load.c
The Astroidea XMF module Astro.xmf (attached) uses the pattern loop effect twice at position 16 / pattern 15. Without this fix, the first loop will play correctly but the last one only play once. Besides that, Xmp think there are two sub-songs / sequences.
The fix make sure that the E60 effect is stored as an event, which indicate the start of the pattern loop.
[Astro.zip](https://github.com/user-attachments/files/19820378/Astro.zip)
> Fix pattern loop effect in Astroidea XMF

- src/loaders/masi_load.c
The Extreme Pinball modules in Epic MegaGames MASI format could not be played at all. Xmp just stopped immediately. This fix will make Xmp to load these module correctly.
The problem was the parsing of the subchunks in the SONG chunk.
Link to modules:
https://modland.com/pub/modules/Epic%20Megagames%20MASI/Robert%20Allen/
> Fix loading of Extreme Pinball modules

- src/loaders/far_load.c
Megan Potter's name has been updated e.g. across the entire KallistiOS source, so I've changed the comment here to match.
(Leaving the format documentation as-is for now, but it may be worth updating as well.)
> Fix attribution in far_load.c.

- docs/Changelog
- docs/libxmp.rst
- src/common.h
- src/control.c
- src/player.c
- src/scan.c
- test-dev/Makefile.in
- test-dev/all_tests.txt
- test-dev/libxmp_fuzz.c
- test-dev/test_api_next_position.c
- test-dev/test_api_prev_position.c
- test-dev/test_api_set_position.c
- test-dev/test_api_set_row.c
- test-dev/test_player_scan.c
+ Fix crashes when using `xmp_set_position` to set a negative position. This now returns `-XMP_ERROR_INVALID` instead.
+ Fix crashes when using `xmp_set_row` to set a negative row. This now returns `-XMP_ERROR_INVALID` instead.
+ Fix hangs when `xmp_prev_position` is used on the first position of a sequence which is preceded by an S3M/IT skip marker.
+ Fix hangs when seeking to S3M/IT end-of-module markers assigned to a non-existent sequences.
+ Fix out-of-bounds reads past the end of `mod->xxo` when `xmp_next_position` is used at the end of a 256 position module.
+ Added `xmp_next_position` regression test.
+ Added `xmp_set_position`, `xmp_next_position`, `xmp_prev_position`, `xmp_set_row`, and `xmp_seek_time` calls to libxmp_fuzz.c.
+ Added …
> Fix bugs in position seek functions and clarify API seek edge cases.

- docs/Changelog
- src/loaders/okt_load.c
- src/loaders/sfx_load.c
The Oktalyzer and SFX loaders are the only remaining loaders that needlessly generate `idiv` instructions, so I've rewritten both to instead use an inner row loop. These are the last two "easy" `idiv` removals, as the rest are necessary for instrument/effects conversion (Startrekker, Digital Tracker, AMOS Music Bank, etc.) or are embedded in the player code and Paula mixers. The player divisions are extremely hard to miss and can be dealt with some other time.
Closes #400.
> Remove remaining loader pattern loop integer division usage.

- docs/Changelog
- docs/libxmp.rst
- lite/Changelog
- src/common.h
- src/effects.c
- src/far_extras.c
- src/load_helpers.c
- src/player.c
- src/scan.c
- test-dev/test_api_set_tempo_factor.c
Previously, the value set by xmp_set_tempo_factor was being applied immediately to frame time calculations, but not to the scanned sequence and order time calculations. This would result in playback time incorrectly "drifting" and then resetting when using tempo factors aside from the module's original tempo factor.
The time factor used for the most recent scan is now stored and used to generate the frame time when calculating the playback time. This allows users to alter the tempo factor with xmp_set_tempo_factor and get consistent playback times based on the original scan.
Calling xmp_scan_module will update the frame time calculation to use the new tempo factor (same as it updated the sequence/order time values prior). I've updated libxmp.rst to hopefully clarify some of these …
> xmp_set_tempo_factor no longer modifies frame time prior to rescan.

- src/filter.c
This PR updates the comment block preceding `resonance_table` in `filter.c` to include the formula that produced the numbers.
> Add the formula for resonance_table to filter.c

- .github/workflows/regression.yaml
- Makefile.in
- Makefile.lnx
- lite/Makefile.in
- lite/Makefile.lnx
- lite/watcom.mif.in
- watcom.mif
- watcom.mif.in
Tested by generating an xmp binary for i686-linux with oss audio and running on i686- and x86_64-linux.
> add OpenWatcom makefiles targeting Linux

- src/filter.c
- src/flow.c
- src/med_extras.c
```
src/player.c:863: undefined reference to `libxmp_med_hold_hack'
src/player.lo: In function `process_frequency':
src/player.c:1317: undefined reference to `libxmp_filter_setup'
src/scan.lo: In function `scan_module':
src/scan.c:534: undefined reference to `libxmp_process_pattern_break'
src/scan.c:544: undefined reference to `libxmp_process_pattern_jump'
src/scan.c:560: undefined reference to `libxmp_process_pattern_break'
src/scan.c:572: undefined reference to `libxmp_process_line_jump'
src/scan.c:595: undefined reference to `libxmp_process_pattern_loop'
src/effects.lo: In function `libxmp_process_fx':
src/effects.c:571: undefined reference to `libxmp_process_pattern_break'
src/effects.c:367: undefined reference to `libxmp_process_pattern_jump'
src/effects.c:377: undefined reference to …
```
> Fix link failures in builds C++ with compilers.

- Makefile.vc
- cmake/libxmp-sources.cmake
- lite/src/Makefile
- src/Makefile
- src/bitrot/loaders/ssmt_load.c
- src/common.h
- src/loaders/common.c
- src/loaders/flt_load.c
- src/loaders/loader.h
- src/loaders/med4_load.c
- src/loaders/mfp_load.c
- src/loaders/mmd_common.c
- src/loaders/mod_load.c
- src/loaders/stm_load.c
- src/path.c
- src/path.h
- src/tempfile.c
- test-dev/CMakeLists.txt
- test-dev/Makefile.in
- test-dev/Makefile.vc
- test-dev/all_tests.txt
- test-dev/test_path.c
- watcom.mif
This patch replaces most instances of fixed-size stack buffers
for paths with heap path functions, offering the following benefits:
* Full path buffers are no longer placed on the stack. In Linux,
`XMP_MAXPATH` is defined to 4096(!), and for most other platforms
it is defined to 1024. In some cases, libxmp would create multiple
of these buffers. For comparison, the default stack size for new
threads in dkP SDKs is 8192.
* Path sizes are no longer limited by an arbitrary value defined in
a header somewhere. Aside from old Windows versions, these values
seem to rarely have any basis in reality.
* Since this uses dedicated functions, I added a slash-cleaning
routine, since this can sometimes be a problem in console SDKs.
Previously, libxmp was putting hardcoded slashes in `snprintf` calls.
I …
> Add libxmp_path functions to replace XMP_MAXPATH.
